//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi DESKTOP-J5VELTF\DELL luc 10:47:31 ngay 24/12/2021
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace PSC_ERP_Business.Main.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PSC_ERPModel", Name="AppUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AppUser : PSC_ERP_Core.BaseEntityObject//EntityObject
    {
    	public AppUser()
    	{
    
    	}
        #region Factory Method
    
        /// <summary>
        /// Create a new AppUser object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        public static AppUser CreateAppUser(int userID)
        {
            AppUser appUser = new AppUser();
            appUser.UserID = userID;
            return appUser;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return _userID;
            }
            set
            {
                if (_userID != value)
                {
        			int oldValue =  _userID;
        			bool stopChanging = false;
                    On_UserID_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("UserID");
        			if(!stopChanging)
        			{
        				_userID = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("UserID");
        				On_UserID_Changed(oldValue, _userID);//\\
        			}
                }
            }
        }
    	public static String UserID_PropertyName { get { return "UserID"; } }
        private int _userID;
        partial void On_UserID_Changing(int currentValue, ref int newValue, ref bool stopChanging);
        partial void On_UserID_Changed(int oldValue, int currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return _userName;
            }
            set
            {
    			string oldValue =  _userName;
    			bool stopChanging = false;
                On_UserName_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("UserName");
    			if(!stopChanging)
    			{
    				_userName = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("UserName");
    				On_UserName_Changed(oldValue, _userName);//\\
    			}
            }
        }
    	public static String UserName_PropertyName { get { return "UserName"; } }
        private string _userName;
        partial void On_UserName_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_UserName_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string Password
        {
            get
            {
                return _password;
            }
            set
            {
    			string oldValue =  _password;
    			bool stopChanging = false;
                On_Password_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("Password");
    			if(!stopChanging)
    			{
    				_password = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("Password");
    				On_Password_Changed(oldValue, _password);//\\
    			}
            }
        }
    	public static String Password_PropertyName { get { return "Password"; } }
        private string _password;
        partial void On_Password_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_Password_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string UserInterfaceTheme
        {
            get
            {
                return _userInterfaceTheme;
            }
            set
            {
    			string oldValue =  _userInterfaceTheme;
    			bool stopChanging = false;
                On_UserInterfaceTheme_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("UserInterfaceTheme");
    			if(!stopChanging)
    			{
    				_userInterfaceTheme = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("UserInterfaceTheme");
    				On_UserInterfaceTheme_Changed(oldValue, _userInterfaceTheme);//\\
    			}
            }
        }
    	public static String UserInterfaceTheme_PropertyName { get { return "UserInterfaceTheme"; } }
        private string _userInterfaceTheme;
        partial void On_UserInterfaceTheme_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_UserInterfaceTheme_Changed(string oldValue, string currentValue);

        #endregion

    }
}
