//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi DESKTOP-J5VELTF\DELL luc 10:47:31 ngay 24/12/2021
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace PSC_ERP_Business.Main.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PSC_ERPModel", Name="tblCongCuDungCu_PhongBan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblCongCuDungCu_PhongBan : PSC_ERP_Core.BaseEntityObject//EntityObject
    {
    	public tblCongCuDungCu_PhongBan()
    	{
    
    	}
        #region Factory Method
    
        /// <summary>
        /// Create a new tblCongCuDungCu_PhongBan object.
        /// </summary>
        /// <param name="maPhanBo">Initial value of the MaPhanBo property.</param>
        public static tblCongCuDungCu_PhongBan CreatetblCongCuDungCu_PhongBan(int maPhanBo)
        {
            tblCongCuDungCu_PhongBan tblCongCuDungCu_PhongBan = new tblCongCuDungCu_PhongBan();
            tblCongCuDungCu_PhongBan.MaPhanBo = maPhanBo;
            return tblCongCuDungCu_PhongBan;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public int MaPhanBo
        {
            get
            {
                return _maPhanBo;
            }
            set
            {
                if (_maPhanBo != value)
                {
        			int oldValue =  _maPhanBo;
        			bool stopChanging = false;
                    On_MaPhanBo_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("MaPhanBo");
        			if(!stopChanging)
        			{
        				_maPhanBo = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("MaPhanBo");
        				On_MaPhanBo_Changed(oldValue, _maPhanBo);//\\
        			}
                }
            }
        }
    	public static String MaPhanBo_PropertyName { get { return "MaPhanBo"; } }
        private int _maPhanBo;
        partial void On_MaPhanBo_Changing(int currentValue, ref int newValue, ref bool stopChanging);
        partial void On_MaPhanBo_Changed(int oldValue, int currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaCongCuDungCu
        {
            get
            {
                return _maCongCuDungCu;
            }
            set
            {
    			Nullable<int> oldValue =  _maCongCuDungCu;
    			bool stopChanging = false;
                On_MaCongCuDungCu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaCongCuDungCu");
    			if(!stopChanging)
    			{
    				_maCongCuDungCu = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaCongCuDungCu");
    				On_MaCongCuDungCu_Changed(oldValue, _maCongCuDungCu);//\\
    			}
            }
        }
    	public static String MaCongCuDungCu_PropertyName { get { return "MaCongCuDungCu"; } }
        private Nullable<int> _maCongCuDungCu;
        partial void On_MaCongCuDungCu_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaCongCuDungCu_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaBoPhan
        {
            get
            {
                return _maBoPhan;
            }
            set
            {
    			Nullable<int> oldValue =  _maBoPhan;
    			bool stopChanging = false;
                On_MaBoPhan_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaBoPhan");
    			if(!stopChanging)
    			{
    				_maBoPhan = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaBoPhan");
    				On_MaBoPhan_Changed(oldValue, _maBoPhan);//\\
    			}
            }
        }
    	public static String MaBoPhan_PropertyName { get { return "MaBoPhan"; } }
        private Nullable<int> _maBoPhan;
        partial void On_MaBoPhan_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaBoPhan_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> NgayNhan
        {
            get
            {
                return _ngayNhan;
            }
            set
            {
    			Nullable<System.DateTime> oldValue =  _ngayNhan;
    			bool stopChanging = false;
                On_NgayNhan_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("NgayNhan");
    			if(!stopChanging)
    			{
    				_ngayNhan = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("NgayNhan");
    				On_NgayNhan_Changed(oldValue, _ngayNhan);//\\
    			}
            }
        }
    	public static String NgayNhan_PropertyName { get { return "NgayNhan"; } }
        private Nullable<System.DateTime> _ngayNhan;
        partial void On_NgayNhan_Changing(Nullable<System.DateTime> currentValue, ref Nullable<System.DateTime> newValue, ref bool stopChanging);
        partial void On_NgayNhan_Changed(Nullable<System.DateTime> oldValue, Nullable<System.DateTime> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> DenNgay
        {
            get
            {
                return _denNgay;
            }
            set
            {
    			Nullable<System.DateTime> oldValue =  _denNgay;
    			bool stopChanging = false;
                On_DenNgay_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("DenNgay");
    			if(!stopChanging)
    			{
    				_denNgay = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("DenNgay");
    				On_DenNgay_Changed(oldValue, _denNgay);//\\
    			}
            }
        }
    	public static String DenNgay_PropertyName { get { return "DenNgay"; } }
        private Nullable<System.DateTime> _denNgay;
        partial void On_DenNgay_Changing(Nullable<System.DateTime> currentValue, ref Nullable<System.DateTime> newValue, ref bool stopChanging);
        partial void On_DenNgay_Changed(Nullable<System.DateTime> oldValue, Nullable<System.DateTime> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> PmCuMaPhongBan
        {
            get
            {
                return _pmCuMaPhongBan;
            }
            set
            {
    			Nullable<int> oldValue =  _pmCuMaPhongBan;
    			bool stopChanging = false;
                On_PmCuMaPhongBan_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("PmCuMaPhongBan");
    			if(!stopChanging)
    			{
    				_pmCuMaPhongBan = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("PmCuMaPhongBan");
    				On_PmCuMaPhongBan_Changed(oldValue, _pmCuMaPhongBan);//\\
    			}
            }
        }
    	public static String PmCuMaPhongBan_PropertyName { get { return "PmCuMaPhongBan"; } }
        private Nullable<int> _pmCuMaPhongBan;
        partial void On_PmCuMaPhongBan_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_PmCuMaPhongBan_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaCTDieuChuyenNoiBo
        {
            get
            {
                return _maCTDieuChuyenNoiBo;
            }
            set
            {
    			Nullable<int> oldValue =  _maCTDieuChuyenNoiBo;
    			bool stopChanging = false;
                On_MaCTDieuChuyenNoiBo_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaCTDieuChuyenNoiBo");
    			if(!stopChanging)
    			{
    				_maCTDieuChuyenNoiBo = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaCTDieuChuyenNoiBo");
    				On_MaCTDieuChuyenNoiBo_Changed(oldValue, _maCTDieuChuyenNoiBo);//\\
    			}
            }
        }
    	public static String MaCTDieuChuyenNoiBo_PropertyName { get { return "MaCTDieuChuyenNoiBo"; } }
        private Nullable<int> _maCTDieuChuyenNoiBo;
        partial void On_MaCTDieuChuyenNoiBo_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaCTDieuChuyenNoiBo_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<long> MaPhieuNhapXuat
        {
            get
            {
                return _maPhieuNhapXuat;
            }
            set
            {
    			Nullable<long> oldValue =  _maPhieuNhapXuat;
    			bool stopChanging = false;
                On_MaPhieuNhapXuat_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaPhieuNhapXuat");
    			if(!stopChanging)
    			{
    				_maPhieuNhapXuat = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaPhieuNhapXuat");
    				On_MaPhieuNhapXuat_Changed(oldValue, _maPhieuNhapXuat);//\\
    			}
            }
        }
    	public static String MaPhieuNhapXuat_PropertyName { get { return "MaPhieuNhapXuat"; } }
        private Nullable<long> _maPhieuNhapXuat;
        partial void On_MaPhieuNhapXuat_Changing(Nullable<long> currentValue, ref Nullable<long> newValue, ref bool stopChanging);
        partial void On_MaPhieuNhapXuat_Changed(Nullable<long> oldValue, Nullable<long> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<bool> TuExcel2014
        {
            get
            {
                return _tuExcel2014;
            }
            set
            {
    			Nullable<bool> oldValue =  _tuExcel2014;
    			bool stopChanging = false;
                On_TuExcel2014_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TuExcel2014");
    			if(!stopChanging)
    			{
    				_tuExcel2014 = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("TuExcel2014");
    				On_TuExcel2014_Changed(oldValue, _tuExcel2014);//\\
    			}
            }
        }
    	public static String TuExcel2014_PropertyName { get { return "TuExcel2014"; } }
        private Nullable<bool> _tuExcel2014;
        partial void On_TuExcel2014_Changing(Nullable<bool> currentValue, ref Nullable<bool> newValue, ref bool stopChanging);
        partial void On_TuExcel2014_Changed(Nullable<bool> oldValue, Nullable<bool> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaTruong
        {
            get
            {
                return _maTruong;
            }
            set
            {
    			Nullable<int> oldValue =  _maTruong;
    			bool stopChanging = false;
                On_MaTruong_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaTruong");
    			if(!stopChanging)
    			{
    				_maTruong = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaTruong");
    				On_MaTruong_Changed(oldValue, _maTruong);//\\
    			}
            }
        }
    	public static String MaTruong_PropertyName { get { return "MaTruong"; } }
        private Nullable<int> _maTruong;
        partial void On_MaTruong_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaTruong_Changed(Nullable<int> oldValue, Nullable<int> currentValue);

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PSC_ERPModel", "FK_tblCongCuDungCu_PhongBan_tblCongCuDungCu", "tblCongCuDungCu")]
        public tblCongCuDungCu tblCongCuDungCu
        {//test
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCongCuDungCu>("PSC_ERPModel.FK_tblCongCuDungCu_PhongBan_tblCongCuDungCu", "tblCongCuDungCu").Value;
            }
            set
            {
    			bool stopChanging = false;
    			On_tblCongCuDungCu_Changing(ref value, ref stopChanging);//\\//
    			if(!stopChanging)
    			{
    				((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCongCuDungCu>("PSC_ERPModel.FK_tblCongCuDungCu_PhongBan_tblCongCuDungCu", "tblCongCuDungCu").Value = value;
    				On_tblCongCuDungCu_Changed(this.tblCongCuDungCu);//\\//
    			}
    	    }
        }
    	public static String tblCongCuDungCu_ReferencePropertyName { get { return "tblCongCuDungCu"; } }
    	partial void On_tblCongCuDungCu_Changing(ref tblCongCuDungCu newValue, ref bool stopChanging);
    	partial void On_tblCongCuDungCu_Changed(tblCongCuDungCu currentValue);
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblCongCuDungCu> tblCongCuDungCuReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCongCuDungCu>("PSC_ERPModel.FK_tblCongCuDungCu_PhongBan_tblCongCuDungCu", "tblCongCuDungCu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblCongCuDungCu>("PSC_ERPModel.FK_tblCongCuDungCu_PhongBan_tblCongCuDungCu", "tblCongCuDungCu", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PSC_ERPModel", "FK_tblCongCuDungCu_PhongBan_tblPhieuNhapXuat", "tblPhieuNhapXuat")]
        public tblPhieuNhapXuat tblPhieuNhapXuat
        {//test
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblPhieuNhapXuat>("PSC_ERPModel.FK_tblCongCuDungCu_PhongBan_tblPhieuNhapXuat", "tblPhieuNhapXuat").Value;
            }
            set
            {
    			bool stopChanging = false;
    			On_tblPhieuNhapXuat_Changing(ref value, ref stopChanging);//\\//
    			if(!stopChanging)
    			{
    				((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblPhieuNhapXuat>("PSC_ERPModel.FK_tblCongCuDungCu_PhongBan_tblPhieuNhapXuat", "tblPhieuNhapXuat").Value = value;
    				On_tblPhieuNhapXuat_Changed(this.tblPhieuNhapXuat);//\\//
    			}
    	    }
        }
    	public static String tblPhieuNhapXuat_ReferencePropertyName { get { return "tblPhieuNhapXuat"; } }
    	partial void On_tblPhieuNhapXuat_Changing(ref tblPhieuNhapXuat newValue, ref bool stopChanging);
    	partial void On_tblPhieuNhapXuat_Changed(tblPhieuNhapXuat currentValue);
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblPhieuNhapXuat> tblPhieuNhapXuatReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblPhieuNhapXuat>("PSC_ERPModel.FK_tblCongCuDungCu_PhongBan_tblPhieuNhapXuat", "tblPhieuNhapXuat");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblPhieuNhapXuat>("PSC_ERPModel.FK_tblCongCuDungCu_PhongBan_tblPhieuNhapXuat", "tblPhieuNhapXuat", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PSC_ERPModel", "FK_tblCongCuDungCu_PhongBan_tblBoPhanERPNew", "tblBoPhanERPNew")]
        public tblBoPhanERPNew tblBoPhanERPNew
        {//test
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblBoPhanERPNew>("PSC_ERPModel.FK_tblCongCuDungCu_PhongBan_tblBoPhanERPNew", "tblBoPhanERPNew").Value;
            }
            set
            {
    			bool stopChanging = false;
    			On_tblBoPhanERPNew_Changing(ref value, ref stopChanging);//\\//
    			if(!stopChanging)
    			{
    				((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblBoPhanERPNew>("PSC_ERPModel.FK_tblCongCuDungCu_PhongBan_tblBoPhanERPNew", "tblBoPhanERPNew").Value = value;
    				On_tblBoPhanERPNew_Changed(this.tblBoPhanERPNew);//\\//
    			}
    	    }
        }
    	public static String tblBoPhanERPNew_ReferencePropertyName { get { return "tblBoPhanERPNew"; } }
    	partial void On_tblBoPhanERPNew_Changing(ref tblBoPhanERPNew newValue, ref bool stopChanging);
    	partial void On_tblBoPhanERPNew_Changed(tblBoPhanERPNew currentValue);
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblBoPhanERPNew> tblBoPhanERPNewReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblBoPhanERPNew>("PSC_ERPModel.FK_tblCongCuDungCu_PhongBan_tblBoPhanERPNew", "tblBoPhanERPNew");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblBoPhanERPNew>("PSC_ERPModel.FK_tblCongCuDungCu_PhongBan_tblBoPhanERPNew", "tblBoPhanERPNew", value);
                }
            }
        }

        #endregion

    }
}
