//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi DESKTOP-J5VELTF\DELL luc 10:47:31 ngay 24/12/2021
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace PSC_ERP_Business.Main.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PSC_ERPModel", Name="tblCongTy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblCongTy : PSC_ERP_Core.BaseEntityObject//EntityObject
    {
    	public tblCongTy()
    	{
    
    	}
        #region Factory Method
    
        /// <summary>
        /// Create a new tblCongTy object.
        /// </summary>
        /// <param name="maCongTy">Initial value of the MaCongTy property.</param>
        public static tblCongTy CreatetblCongTy(int maCongTy)
        {
            tblCongTy tblCongTy = new tblCongTy();
            tblCongTy.MaCongTy = maCongTy;
            return tblCongTy;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public int MaCongTy
        {
            get
            {
                return _maCongTy;
            }
            set
            {
                if (_maCongTy != value)
                {
        			int oldValue =  _maCongTy;
        			bool stopChanging = false;
                    On_MaCongTy_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("MaCongTy");
        			if(!stopChanging)
        			{
        				_maCongTy = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("MaCongTy");
        				On_MaCongTy_Changed(oldValue, _maCongTy);//\\
        			}
                }
            }
        }
    	public static String MaCongTy_PropertyName { get { return "MaCongTy"; } }
        private int _maCongTy;
        partial void On_MaCongTy_Changing(int currentValue, ref int newValue, ref bool stopChanging);
        partial void On_MaCongTy_Changed(int oldValue, int currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string MaCongTyQuanLy
        {
            get
            {
                return _maCongTyQuanLy;
            }
            set
            {
    			string oldValue =  _maCongTyQuanLy;
    			bool stopChanging = false;
                On_MaCongTyQuanLy_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaCongTyQuanLy");
    			if(!stopChanging)
    			{
    				_maCongTyQuanLy = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("MaCongTyQuanLy");
    				On_MaCongTyQuanLy_Changed(oldValue, _maCongTyQuanLy);//\\
    			}
            }
        }
    	public static String MaCongTyQuanLy_PropertyName { get { return "MaCongTyQuanLy"; } }
        private string _maCongTyQuanLy;
        partial void On_MaCongTyQuanLy_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_MaCongTyQuanLy_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string TenCongTy
        {
            get
            {
                return _tenCongTy;
            }
            set
            {
    			string oldValue =  _tenCongTy;
    			bool stopChanging = false;
                On_TenCongTy_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TenCongTy");
    			if(!stopChanging)
    			{
    				_tenCongTy = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("TenCongTy");
    				On_TenCongTy_Changed(oldValue, _tenCongTy);//\\
    			}
            }
        }
    	public static String TenCongTy_PropertyName { get { return "TenCongTy"; } }
        private string _tenCongTy;
        partial void On_TenCongTy_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenCongTy_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string TenVietTat
        {
            get
            {
                return _tenVietTat;
            }
            set
            {
    			string oldValue =  _tenVietTat;
    			bool stopChanging = false;
                On_TenVietTat_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TenVietTat");
    			if(!stopChanging)
    			{
    				_tenVietTat = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("TenVietTat");
    				On_TenVietTat_Changed(oldValue, _tenVietTat);//\\
    			}
            }
        }
    	public static String TenVietTat_PropertyName { get { return "TenVietTat"; } }
        private string _tenVietTat;
        partial void On_TenVietTat_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenVietTat_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string TenTiengAnh
        {
            get
            {
                return _tenTiengAnh;
            }
            set
            {
    			string oldValue =  _tenTiengAnh;
    			bool stopChanging = false;
                On_TenTiengAnh_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TenTiengAnh");
    			if(!stopChanging)
    			{
    				_tenTiengAnh = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("TenTiengAnh");
    				On_TenTiengAnh_Changed(oldValue, _tenTiengAnh);//\\
    			}
            }
        }
    	public static String TenTiengAnh_PropertyName { get { return "TenTiengAnh"; } }
        private string _tenTiengAnh;
        partial void On_TenTiengAnh_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenTiengAnh_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string MaSoThue
        {
            get
            {
                return _maSoThue;
            }
            set
            {
    			string oldValue =  _maSoThue;
    			bool stopChanging = false;
                On_MaSoThue_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaSoThue");
    			if(!stopChanging)
    			{
    				_maSoThue = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("MaSoThue");
    				On_MaSoThue_Changed(oldValue, _maSoThue);//\\
    			}
            }
        }
    	public static String MaSoThue_PropertyName { get { return "MaSoThue"; } }
        private string _maSoThue;
        partial void On_MaSoThue_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_MaSoThue_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string SoTaiKhoan
        {
            get
            {
                return _soTaiKhoan;
            }
            set
            {
    			string oldValue =  _soTaiKhoan;
    			bool stopChanging = false;
                On_SoTaiKhoan_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("SoTaiKhoan");
    			if(!stopChanging)
    			{
    				_soTaiKhoan = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("SoTaiKhoan");
    				On_SoTaiKhoan_Changed(oldValue, _soTaiKhoan);//\\
    			}
            }
        }
    	public static String SoTaiKhoan_PropertyName { get { return "SoTaiKhoan"; } }
        private string _soTaiKhoan;
        partial void On_SoTaiKhoan_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_SoTaiKhoan_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public byte[] Logo
        {
            get
            {
                return StructuralObject.GetValidValue(_logo);
            }
            set
            {
    			byte[] oldValue =  _logo;
    			bool stopChanging = false;
                On_Logo_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("Logo");
    			if(!stopChanging)
    			{
    				_logo = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("Logo");
    				On_Logo_Changed(oldValue, _logo);//\\
    			}
            }
        }
    	public static String Logo_PropertyName { get { return "Logo"; } }
        private byte[] _logo;
        partial void On_Logo_Changing(byte[] currentValue, ref byte[] newValue, ref bool stopChanging);
        partial void On_Logo_Changed(byte[] oldValue, byte[] currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string DienThoai
        {
            get
            {
                return _dienThoai;
            }
            set
            {
    			string oldValue =  _dienThoai;
    			bool stopChanging = false;
                On_DienThoai_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("DienThoai");
    			if(!stopChanging)
    			{
    				_dienThoai = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("DienThoai");
    				On_DienThoai_Changed(oldValue, _dienThoai);//\\
    			}
            }
        }
    	public static String DienThoai_PropertyName { get { return "DienThoai"; } }
        private string _dienThoai;
        partial void On_DienThoai_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_DienThoai_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string DienThoai1
        {
            get
            {
                return _dienThoai1;
            }
            set
            {
    			string oldValue =  _dienThoai1;
    			bool stopChanging = false;
                On_DienThoai1_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("DienThoai1");
    			if(!stopChanging)
    			{
    				_dienThoai1 = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("DienThoai1");
    				On_DienThoai1_Changed(oldValue, _dienThoai1);//\\
    			}
            }
        }
    	public static String DienThoai1_PropertyName { get { return "DienThoai1"; } }
        private string _dienThoai1;
        partial void On_DienThoai1_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_DienThoai1_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaNganHang
        {
            get
            {
                return _maNganHang;
            }
            set
            {
    			Nullable<int> oldValue =  _maNganHang;
    			bool stopChanging = false;
                On_MaNganHang_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaNganHang");
    			if(!stopChanging)
    			{
    				_maNganHang = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaNganHang");
    				On_MaNganHang_Changed(oldValue, _maNganHang);//\\
    			}
            }
        }
    	public static String MaNganHang_PropertyName { get { return "MaNganHang"; } }
        private Nullable<int> _maNganHang;
        partial void On_MaNganHang_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaNganHang_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string Fax
        {
            get
            {
                return _fax;
            }
            set
            {
    			string oldValue =  _fax;
    			bool stopChanging = false;
                On_Fax_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("Fax");
    			if(!stopChanging)
    			{
    				_fax = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("Fax");
    				On_Fax_Changed(oldValue, _fax);//\\
    			}
            }
        }
    	public static String Fax_PropertyName { get { return "Fax"; } }
        private string _fax;
        partial void On_Fax_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_Fax_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string Website
        {
            get
            {
                return _website;
            }
            set
            {
    			string oldValue =  _website;
    			bool stopChanging = false;
                On_Website_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("Website");
    			if(!stopChanging)
    			{
    				_website = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("Website");
    				On_Website_Changed(oldValue, _website);//\\
    			}
            }
        }
    	public static String Website_PropertyName { get { return "Website"; } }
        private string _website;
        partial void On_Website_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_Website_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string Email
        {
            get
            {
                return _email;
            }
            set
            {
    			string oldValue =  _email;
    			bool stopChanging = false;
                On_Email_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("Email");
    			if(!stopChanging)
    			{
    				_email = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("Email");
    				On_Email_Changed(oldValue, _email);//\\
    			}
            }
        }
    	public static String Email_PropertyName { get { return "Email"; } }
        private string _email;
        partial void On_Email_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_Email_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string DiaChi
        {
            get
            {
                return _diaChi;
            }
            set
            {
    			string oldValue =  _diaChi;
    			bool stopChanging = false;
                On_DiaChi_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("DiaChi");
    			if(!stopChanging)
    			{
    				_diaChi = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("DiaChi");
    				On_DiaChi_Changed(oldValue, _diaChi);//\\
    			}
            }
        }
    	public static String DiaChi_PropertyName { get { return "DiaChi"; } }
        private string _diaChi;
        partial void On_DiaChi_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_DiaChi_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string DiaChi1
        {
            get
            {
                return _diaChi1;
            }
            set
            {
    			string oldValue =  _diaChi1;
    			bool stopChanging = false;
                On_DiaChi1_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("DiaChi1");
    			if(!stopChanging)
    			{
    				_diaChi1 = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("DiaChi1");
    				On_DiaChi1_Changed(oldValue, _diaChi1);//\\
    			}
            }
        }
    	public static String DiaChi1_PropertyName { get { return "DiaChi1"; } }
        private string _diaChi1;
        partial void On_DiaChi1_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_DiaChi1_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string GhiChu
        {
            get
            {
                return _ghiChu;
            }
            set
            {
    			string oldValue =  _ghiChu;
    			bool stopChanging = false;
                On_GhiChu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("GhiChu");
    			if(!stopChanging)
    			{
    				_ghiChu = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("GhiChu");
    				On_GhiChu_Changed(oldValue, _ghiChu);//\\
    			}
            }
        }
    	public static String GhiChu_PropertyName { get { return "GhiChu"; } }
        private string _ghiChu;
        partial void On_GhiChu_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_GhiChu_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string SoDVSDNS
        {
            get
            {
                return _soDVSDNS;
            }
            set
            {
    			string oldValue =  _soDVSDNS;
    			bool stopChanging = false;
                On_SoDVSDNS_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("SoDVSDNS");
    			if(!stopChanging)
    			{
    				_soDVSDNS = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("SoDVSDNS");
    				On_SoDVSDNS_Changed(oldValue, _soDVSDNS);//\\
    			}
            }
        }
    	public static String SoDVSDNS_PropertyName { get { return "SoDVSDNS"; } }
        private string _soDVSDNS;
        partial void On_SoDVSDNS_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_SoDVSDNS_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> NgayChanSo
        {
            get
            {
                return _ngayChanSo;
            }
            set
            {
    			Nullable<System.DateTime> oldValue =  _ngayChanSo;
    			bool stopChanging = false;
                On_NgayChanSo_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("NgayChanSo");
    			if(!stopChanging)
    			{
    				_ngayChanSo = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("NgayChanSo");
    				On_NgayChanSo_Changed(oldValue, _ngayChanSo);//\\
    			}
            }
        }
    	public static String NgayChanSo_PropertyName { get { return "NgayChanSo"; } }
        private Nullable<System.DateTime> _ngayChanSo;
        partial void On_NgayChanSo_Changing(Nullable<System.DateTime> currentValue, ref Nullable<System.DateTime> newValue, ref bool stopChanging);
        partial void On_NgayChanSo_Changed(Nullable<System.DateTime> oldValue, Nullable<System.DateTime> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.Guid> OidHRM
        {
            get
            {
                return _oidHRM;
            }
            set
            {
    			Nullable<System.Guid> oldValue =  _oidHRM;
    			bool stopChanging = false;
                On_OidHRM_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("OidHRM");
    			if(!stopChanging)
    			{
    				_oidHRM = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("OidHRM");
    				On_OidHRM_Changed(oldValue, _oidHRM);//\\
    			}
            }
        }
    	public static String OidHRM_PropertyName { get { return "OidHRM"; } }
        private Nullable<System.Guid> _oidHRM;
        partial void On_OidHRM_Changing(Nullable<System.Guid> currentValue, ref Nullable<System.Guid> newValue, ref bool stopChanging);
        partial void On_OidHRM_Changed(Nullable<System.Guid> oldValue, Nullable<System.Guid> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<bool> CongThue
        {
            get
            {
                return _congThue;
            }
            set
            {
    			Nullable<bool> oldValue =  _congThue;
    			bool stopChanging = false;
                On_CongThue_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("CongThue");
    			if(!stopChanging)
    			{
    				_congThue = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("CongThue");
    				On_CongThue_Changed(oldValue, _congThue);//\\
    			}
            }
        }
    	public static String CongThue_PropertyName { get { return "CongThue"; } }
        private Nullable<bool> _congThue;
        partial void On_CongThue_Changing(Nullable<bool> currentValue, ref Nullable<bool> newValue, ref bool stopChanging);
        partial void On_CongThue_Changed(Nullable<bool> oldValue, Nullable<bool> currentValue);

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PSC_ERPModel", "FK_tblnsChuongTrinh_tblCongTy", "tblnsChuongTrinh")]
        public EntityCollection<tblnsChuongTrinh> tblnsChuongTrinhs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblnsChuongTrinh>("PSC_ERPModel.FK_tblnsChuongTrinh_tblCongTy", "tblnsChuongTrinh");
            }
            set
            {
                if ((value != null))
                {
    				bool stopChanging = false;
    				On_tblnsChuongTrinhs_Changing(ref value, ref stopChanging);//\\//
    				if(!stopChanging)
    				{
    					((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblnsChuongTrinh>("PSC_ERPModel.FK_tblnsChuongTrinh_tblCongTy", "tblnsChuongTrinh", value);
    					On_tblnsChuongTrinhs_Changed(this.tblnsChuongTrinhs);//\\//
    				}
    			}
            }
        }
    	public static String tblnsChuongTrinhs_EntityCollectionPropertyName { get { return "tblnsChuongTrinhs"; } }
    	partial void On_tblnsChuongTrinhs_Changing(ref EntityCollection<tblnsChuongTrinh> newValue, ref bool stopChanging);
    	partial void On_tblnsChuongTrinhs_Changed(EntityCollection<tblnsChuongTrinh> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PSC_ERPModel", "FK_tblTaiSanCoDinhCaBiet_tblCongTy", "tblTaiSanCoDinhCaBiet")]
        public EntityCollection<tblTaiSanCoDinhCaBiet> tblTaiSanCoDinhCaBiets
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblTaiSanCoDinhCaBiet>("PSC_ERPModel.FK_tblTaiSanCoDinhCaBiet_tblCongTy", "tblTaiSanCoDinhCaBiet");
            }
            set
            {
                if ((value != null))
                {
    				bool stopChanging = false;
    				On_tblTaiSanCoDinhCaBiets_Changing(ref value, ref stopChanging);//\\//
    				if(!stopChanging)
    				{
    					((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblTaiSanCoDinhCaBiet>("PSC_ERPModel.FK_tblTaiSanCoDinhCaBiet_tblCongTy", "tblTaiSanCoDinhCaBiet", value);
    					On_tblTaiSanCoDinhCaBiets_Changed(this.tblTaiSanCoDinhCaBiets);//\\//
    				}
    			}
            }
        }
    	public static String tblTaiSanCoDinhCaBiets_EntityCollectionPropertyName { get { return "tblTaiSanCoDinhCaBiets"; } }
    	partial void On_tblTaiSanCoDinhCaBiets_Changing(ref EntityCollection<tblTaiSanCoDinhCaBiet> newValue, ref bool stopChanging);
    	partial void On_tblTaiSanCoDinhCaBiets_Changed(EntityCollection<tblTaiSanCoDinhCaBiet> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PSC_ERPModel", "FK_tblDanhMucTSCD_tblCongTy", "tblDanhMucTSCD")]
        public EntityCollection<tblDanhMucTSCD> tblDanhMucTSCDs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblDanhMucTSCD>("PSC_ERPModel.FK_tblDanhMucTSCD_tblCongTy", "tblDanhMucTSCD");
            }
            set
            {
                if ((value != null))
                {
    				bool stopChanging = false;
    				On_tblDanhMucTSCDs_Changing(ref value, ref stopChanging);//\\//
    				if(!stopChanging)
    				{
    					((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblDanhMucTSCD>("PSC_ERPModel.FK_tblDanhMucTSCD_tblCongTy", "tblDanhMucTSCD", value);
    					On_tblDanhMucTSCDs_Changed(this.tblDanhMucTSCDs);//\\//
    				}
    			}
            }
        }
    	public static String tblDanhMucTSCDs_EntityCollectionPropertyName { get { return "tblDanhMucTSCDs"; } }
    	partial void On_tblDanhMucTSCDs_Changing(ref EntityCollection<tblDanhMucTSCD> newValue, ref bool stopChanging);
    	partial void On_tblDanhMucTSCDs_Changed(EntityCollection<tblDanhMucTSCD> currentValue);

        #endregion

    }
}
