//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi DESKTOP-J5VELTF\DELL luc 10:47:31 ngay 24/12/2021
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace PSC_ERP_Business.Main.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PSC_ERPModel", Name="tblChungTu_LenhChuyenTien")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblChungTu_LenhChuyenTien : PSC_ERP_Core.BaseEntityObject//EntityObject
    {
    	public tblChungTu_LenhChuyenTien()
    	{
    
    	}
        #region Factory Method
    
        /// <summary>
        /// Create a new tblChungTu_LenhChuyenTien object.
        /// </summary>
        /// <param name="maCT_LenhCT">Initial value of the MaCT_LenhCT property.</param>
        public static tblChungTu_LenhChuyenTien CreatetblChungTu_LenhChuyenTien(long maCT_LenhCT)
        {
            tblChungTu_LenhChuyenTien tblChungTu_LenhChuyenTien = new tblChungTu_LenhChuyenTien();
            tblChungTu_LenhChuyenTien.MaCT_LenhCT = maCT_LenhCT;
            return tblChungTu_LenhChuyenTien;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public long MaCT_LenhCT
        {
            get
            {
                return _maCT_LenhCT;
            }
            set
            {
                if (_maCT_LenhCT != value)
                {
        			long oldValue =  _maCT_LenhCT;
        			bool stopChanging = false;
                    On_MaCT_LenhCT_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("MaCT_LenhCT");
        			if(!stopChanging)
        			{
        				_maCT_LenhCT = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("MaCT_LenhCT");
        				On_MaCT_LenhCT_Changed(oldValue, _maCT_LenhCT);//\\
        			}
                }
            }
        }
    	public static String MaCT_LenhCT_PropertyName { get { return "MaCT_LenhCT"; } }
        private long _maCT_LenhCT;
        partial void On_MaCT_LenhCT_Changing(long currentValue, ref long newValue, ref bool stopChanging);
        partial void On_MaCT_LenhCT_Changed(long oldValue, long currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<long> MaChungTu
        {
            get
            {
                return _maChungTu;
            }
            set
            {
    			Nullable<long> oldValue =  _maChungTu;
    			bool stopChanging = false;
                On_MaChungTu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaChungTu");
    			if(!stopChanging)
    			{
    				_maChungTu = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaChungTu");
    				On_MaChungTu_Changed(oldValue, _maChungTu);//\\
    			}
            }
        }
    	public static String MaChungTu_PropertyName { get { return "MaChungTu"; } }
        private Nullable<long> _maChungTu;
        partial void On_MaChungTu_Changing(Nullable<long> currentValue, ref Nullable<long> newValue, ref bool stopChanging);
        partial void On_MaChungTu_Changed(Nullable<long> oldValue, Nullable<long> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<long> MaLenhCT
        {
            get
            {
                return _maLenhCT;
            }
            set
            {
    			Nullable<long> oldValue =  _maLenhCT;
    			bool stopChanging = false;
                On_MaLenhCT_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaLenhCT");
    			if(!stopChanging)
    			{
    				_maLenhCT = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaLenhCT");
    				On_MaLenhCT_Changed(oldValue, _maLenhCT);//\\
    			}
            }
        }
    	public static String MaLenhCT_PropertyName { get { return "MaLenhCT"; } }
        private Nullable<long> _maLenhCT;
        partial void On_MaLenhCT_Changing(Nullable<long> currentValue, ref Nullable<long> newValue, ref bool stopChanging);
        partial void On_MaLenhCT_Changed(Nullable<long> oldValue, Nullable<long> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> SoTien
        {
            get
            {
                return _soTien;
            }
            set
            {
    			Nullable<decimal> oldValue =  _soTien;
    			bool stopChanging = false;
                On_SoTien_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("SoTien");
    			if(!stopChanging)
    			{
    				_soTien = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("SoTien");
    				On_SoTien_Changed(oldValue, _soTien);//\\
    			}
            }
        }
    	public static String SoTien_PropertyName { get { return "SoTien"; } }
        private Nullable<decimal> _soTien;
        partial void On_SoTien_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_SoTien_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string SoChungTu
        {
            get
            {
                return _soChungTu;
            }
            set
            {
    			string oldValue =  _soChungTu;
    			bool stopChanging = false;
                On_SoChungTu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("SoChungTu");
    			if(!stopChanging)
    			{
    				_soChungTu = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("SoChungTu");
    				On_SoChungTu_Changed(oldValue, _soChungTu);//\\
    			}
            }
        }
    	public static String SoChungTu_PropertyName { get { return "SoChungTu"; } }
        private string _soChungTu;
        partial void On_SoChungTu_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_SoChungTu_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string LyDo
        {
            get
            {
                return _lyDo;
            }
            set
            {
    			string oldValue =  _lyDo;
    			bool stopChanging = false;
                On_LyDo_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("LyDo");
    			if(!stopChanging)
    			{
    				_lyDo = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("LyDo");
    				On_LyDo_Changed(oldValue, _lyDo);//\\
    			}
            }
        }
    	public static String LyDo_PropertyName { get { return "LyDo"; } }
        private string _lyDo;
        partial void On_LyDo_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_LyDo_Changed(string oldValue, string currentValue);

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PSC_ERPModel", "FK_tblChungTu_LenhChuyenTien_tblLenhChuyenTien", "tblLenhChuyenTienNuocNgoai")]
        public tblLenhChuyenTienNuocNgoai tblLenhChuyenTienNuocNgoai
        {//test
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblLenhChuyenTienNuocNgoai>("PSC_ERPModel.FK_tblChungTu_LenhChuyenTien_tblLenhChuyenTien", "tblLenhChuyenTienNuocNgoai").Value;
            }
            set
            {
    			bool stopChanging = false;
    			On_tblLenhChuyenTienNuocNgoai_Changing(ref value, ref stopChanging);//\\//
    			if(!stopChanging)
    			{
    				((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblLenhChuyenTienNuocNgoai>("PSC_ERPModel.FK_tblChungTu_LenhChuyenTien_tblLenhChuyenTien", "tblLenhChuyenTienNuocNgoai").Value = value;
    				On_tblLenhChuyenTienNuocNgoai_Changed(this.tblLenhChuyenTienNuocNgoai);//\\//
    			}
    	    }
        }
    	public static String tblLenhChuyenTienNuocNgoai_ReferencePropertyName { get { return "tblLenhChuyenTienNuocNgoai"; } }
    	partial void On_tblLenhChuyenTienNuocNgoai_Changing(ref tblLenhChuyenTienNuocNgoai newValue, ref bool stopChanging);
    	partial void On_tblLenhChuyenTienNuocNgoai_Changed(tblLenhChuyenTienNuocNgoai currentValue);
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblLenhChuyenTienNuocNgoai> tblLenhChuyenTienNuocNgoaiReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblLenhChuyenTienNuocNgoai>("PSC_ERPModel.FK_tblChungTu_LenhChuyenTien_tblLenhChuyenTien", "tblLenhChuyenTienNuocNgoai");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblLenhChuyenTienNuocNgoai>("PSC_ERPModel.FK_tblChungTu_LenhChuyenTien_tblLenhChuyenTien", "tblLenhChuyenTienNuocNgoai", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PSC_ERPModel", "FK_tblChungTu_LenhChuyenTien_tblChungTu", "tblChungTu")]
        public tblChungTu tblChungTu
        {//test
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblChungTu>("PSC_ERPModel.FK_tblChungTu_LenhChuyenTien_tblChungTu", "tblChungTu").Value;
            }
            set
            {
    			bool stopChanging = false;
    			On_tblChungTu_Changing(ref value, ref stopChanging);//\\//
    			if(!stopChanging)
    			{
    				((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblChungTu>("PSC_ERPModel.FK_tblChungTu_LenhChuyenTien_tblChungTu", "tblChungTu").Value = value;
    				On_tblChungTu_Changed(this.tblChungTu);//\\//
    			}
    	    }
        }
    	public static String tblChungTu_ReferencePropertyName { get { return "tblChungTu"; } }
    	partial void On_tblChungTu_Changing(ref tblChungTu newValue, ref bool stopChanging);
    	partial void On_tblChungTu_Changed(tblChungTu currentValue);
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblChungTu> tblChungTuReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblChungTu>("PSC_ERPModel.FK_tblChungTu_LenhChuyenTien_tblChungTu", "tblChungTu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblChungTu>("PSC_ERPModel.FK_tblChungTu_LenhChuyenTien_tblChungTu", "tblChungTu", value);
                }
            }
        }

        #endregion

    }
}
