//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi DESKTOP-J5VELTF\DELL luc 10:47:31 ngay 24/12/2021
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace PSC_ERP_Business.Main.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PSC_ERPModel", Name="tblDiaChi")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblDiaChi : PSC_ERP_Core.BaseEntityObject//EntityObject
    {
    	public tblDiaChi()
    	{
    
    	}
        #region Factory Method
    
        /// <summary>
        /// Create a new tblDiaChi object.
        /// </summary>
        /// <param name="maDiaChi">Initial value of the MaDiaChi property.</param>
        /// <param name="tenDiaChi">Initial value of the TenDiaChi property.</param>
        /// <param name="quanHuyen">Initial value of the QuanHuyen property.</param>
        /// <param name="tinhTP">Initial value of the TinhTP property.</param>
        /// <param name="quocGia">Initial value of the QuocGia property.</param>
        public static tblDiaChi CreatetblDiaChi(int maDiaChi, string tenDiaChi, string quanHuyen, string tinhTP, string quocGia)
        {
            tblDiaChi tblDiaChi = new tblDiaChi();
            tblDiaChi.MaDiaChi = maDiaChi;
            tblDiaChi.TenDiaChi = tenDiaChi;
            tblDiaChi.QuanHuyen = quanHuyen;
            tblDiaChi.TinhTP = tinhTP;
            tblDiaChi.QuocGia = quocGia;
            return tblDiaChi;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public int MaDiaChi
        {
            get
            {
                return _maDiaChi;
            }
            set
            {
                if (_maDiaChi != value)
                {
        			int oldValue =  _maDiaChi;
        			bool stopChanging = false;
                    On_MaDiaChi_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("MaDiaChi");
        			if(!stopChanging)
        			{
        				_maDiaChi = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("MaDiaChi");
        				On_MaDiaChi_Changed(oldValue, _maDiaChi);//\\
        			}
                }
            }
        }
    	public static String MaDiaChi_PropertyName { get { return "MaDiaChi"; } }
        private int _maDiaChi;
        partial void On_MaDiaChi_Changing(int currentValue, ref int newValue, ref bool stopChanging);
        partial void On_MaDiaChi_Changed(int oldValue, int currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public string TenDiaChi
        {
            get
            {
                return _tenDiaChi;
            }
            set
            {
    			string oldValue =  _tenDiaChi;
    			bool stopChanging = false;
                On_TenDiaChi_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TenDiaChi");
    			if(!stopChanging)
    			{
    				_tenDiaChi = StructuralObject.SetValidValue(value, false);
    				ReportPropertyChanged("TenDiaChi");
    				On_TenDiaChi_Changed(oldValue, _tenDiaChi);//\\
    			}
            }
        }
    	public static String TenDiaChi_PropertyName { get { return "TenDiaChi"; } }
        private string _tenDiaChi;
        partial void On_TenDiaChi_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenDiaChi_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public string QuanHuyen
        {
            get
            {
                return _quanHuyen;
            }
            set
            {
    			string oldValue =  _quanHuyen;
    			bool stopChanging = false;
                On_QuanHuyen_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("QuanHuyen");
    			if(!stopChanging)
    			{
    				_quanHuyen = StructuralObject.SetValidValue(value, false);
    				ReportPropertyChanged("QuanHuyen");
    				On_QuanHuyen_Changed(oldValue, _quanHuyen);//\\
    			}
            }
        }
    	public static String QuanHuyen_PropertyName { get { return "QuanHuyen"; } }
        private string _quanHuyen;
        partial void On_QuanHuyen_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_QuanHuyen_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaQuanHuyen
        {
            get
            {
                return _maQuanHuyen;
            }
            set
            {
    			Nullable<int> oldValue =  _maQuanHuyen;
    			bool stopChanging = false;
                On_MaQuanHuyen_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaQuanHuyen");
    			if(!stopChanging)
    			{
    				_maQuanHuyen = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaQuanHuyen");
    				On_MaQuanHuyen_Changed(oldValue, _maQuanHuyen);//\\
    			}
            }
        }
    	public static String MaQuanHuyen_PropertyName { get { return "MaQuanHuyen"; } }
        private Nullable<int> _maQuanHuyen;
        partial void On_MaQuanHuyen_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaQuanHuyen_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaTinhThanh
        {
            get
            {
                return _maTinhThanh;
            }
            set
            {
    			Nullable<int> oldValue =  _maTinhThanh;
    			bool stopChanging = false;
                On_MaTinhThanh_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaTinhThanh");
    			if(!stopChanging)
    			{
    				_maTinhThanh = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaTinhThanh");
    				On_MaTinhThanh_Changed(oldValue, _maTinhThanh);//\\
    			}
            }
        }
    	public static String MaTinhThanh_PropertyName { get { return "MaTinhThanh"; } }
        private Nullable<int> _maTinhThanh;
        partial void On_MaTinhThanh_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaTinhThanh_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public string TinhTP
        {
            get
            {
                return _tinhTP;
            }
            set
            {
    			string oldValue =  _tinhTP;
    			bool stopChanging = false;
                On_TinhTP_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TinhTP");
    			if(!stopChanging)
    			{
    				_tinhTP = StructuralObject.SetValidValue(value, false);
    				ReportPropertyChanged("TinhTP");
    				On_TinhTP_Changed(oldValue, _tinhTP);//\\
    			}
            }
        }
    	public static String TinhTP_PropertyName { get { return "TinhTP"; } }
        private string _tinhTP;
        partial void On_TinhTP_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TinhTP_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaQuocGia
        {
            get
            {
                return _maQuocGia;
            }
            set
            {
    			Nullable<int> oldValue =  _maQuocGia;
    			bool stopChanging = false;
                On_MaQuocGia_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaQuocGia");
    			if(!stopChanging)
    			{
    				_maQuocGia = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaQuocGia");
    				On_MaQuocGia_Changed(oldValue, _maQuocGia);//\\
    			}
            }
        }
    	public static String MaQuocGia_PropertyName { get { return "MaQuocGia"; } }
        private Nullable<int> _maQuocGia;
        partial void On_MaQuocGia_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaQuocGia_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public string QuocGia
        {
            get
            {
                return _quocGia;
            }
            set
            {
    			string oldValue =  _quocGia;
    			bool stopChanging = false;
                On_QuocGia_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("QuocGia");
    			if(!stopChanging)
    			{
    				_quocGia = StructuralObject.SetValidValue(value, false);
    				ReportPropertyChanged("QuocGia");
    				On_QuocGia_Changed(oldValue, _quocGia);//\\
    			}
            }
        }
    	public static String QuocGia_PropertyName { get { return "QuocGia"; } }
        private string _quocGia;
        partial void On_QuocGia_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_QuocGia_Changed(string oldValue, string currentValue);

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PSC_ERPModel", "FK_tblDiaChi_DoiTac_tblDiaChi", "tblDiaChi_DoiTac")]
        public EntityCollection<tblDiaChi_DoiTac> tblDiaChi_DoiTac
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblDiaChi_DoiTac>("PSC_ERPModel.FK_tblDiaChi_DoiTac_tblDiaChi", "tblDiaChi_DoiTac");
            }
            set
            {
                if ((value != null))
                {
    				bool stopChanging = false;
    				On_tblDiaChi_DoiTac_Changing(ref value, ref stopChanging);//\\//
    				if(!stopChanging)
    				{
    					((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblDiaChi_DoiTac>("PSC_ERPModel.FK_tblDiaChi_DoiTac_tblDiaChi", "tblDiaChi_DoiTac", value);
    					On_tblDiaChi_DoiTac_Changed(this.tblDiaChi_DoiTac);//\\//
    				}
    			}
            }
        }
    	public static String tblDiaChi_DoiTac_EntityCollectionPropertyName { get { return "tblDiaChi_DoiTac"; } }
    	partial void On_tblDiaChi_DoiTac_Changing(ref EntityCollection<tblDiaChi_DoiTac> newValue, ref bool stopChanging);
    	partial void On_tblDiaChi_DoiTac_Changed(EntityCollection<tblDiaChi_DoiTac> currentValue);

        #endregion

    }
}
