//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi DESKTOP-J5VELTF\DELL luc 10:47:32 ngay 24/12/2021
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace PSC_ERP_Business.Main.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PSC_ERPModel", Name="tblKhoaSo_MaTaiKhoan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblKhoaSo_MaTaiKhoan : PSC_ERP_Core.BaseEntityObject//EntityObject
    {
    	public tblKhoaSo_MaTaiKhoan()
    	{
    
    	}
        #region Factory Method
    
        /// <summary>
        /// Create a new tblKhoaSo_MaTaiKhoan object.
        /// </summary>
        /// <param name="maKhoaSo">Initial value of the MaKhoaSo property.</param>
        /// <param name="maKy">Initial value of the MaKy property.</param>
        public static tblKhoaSo_MaTaiKhoan CreatetblKhoaSo_MaTaiKhoan(int maKhoaSo, int maKy)
        {
            tblKhoaSo_MaTaiKhoan tblKhoaSo_MaTaiKhoan = new tblKhoaSo_MaTaiKhoan();
            tblKhoaSo_MaTaiKhoan.MaKhoaSo = maKhoaSo;
            tblKhoaSo_MaTaiKhoan.MaKy = maKy;
            return tblKhoaSo_MaTaiKhoan;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public int MaKhoaSo
        {
            get
            {
                return _maKhoaSo;
            }
            set
            {
                if (_maKhoaSo != value)
                {
        			int oldValue =  _maKhoaSo;
        			bool stopChanging = false;
                    On_MaKhoaSo_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("MaKhoaSo");
        			if(!stopChanging)
        			{
        				_maKhoaSo = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("MaKhoaSo");
        				On_MaKhoaSo_Changed(oldValue, _maKhoaSo);//\\
        			}
                }
            }
        }
    	public static String MaKhoaSo_PropertyName { get { return "MaKhoaSo"; } }
        private int _maKhoaSo;
        partial void On_MaKhoaSo_Changing(int currentValue, ref int newValue, ref bool stopChanging);
        partial void On_MaKhoaSo_Changed(int oldValue, int currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public int MaKy
        {
            get
            {
                return _maKy;
            }
            set
            {
    			int oldValue =  _maKy;
    			bool stopChanging = false;
                On_MaKy_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaKy");
    			if(!stopChanging)
    			{
    				_maKy = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaKy");
    				On_MaKy_Changed(oldValue, _maKy);//\\
    			}
            }
        }
    	public static String MaKy_PropertyName { get { return "MaKy"; } }
        private int _maKy;
        partial void On_MaKy_Changing(int currentValue, ref int newValue, ref bool stopChanging);
        partial void On_MaKy_Changed(int oldValue, int currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> UserID
        {
            get
            {
                return _userID;
            }
            set
            {
    			Nullable<int> oldValue =  _userID;
    			bool stopChanging = false;
                On_UserID_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("UserID");
    			if(!stopChanging)
    			{
    				_userID = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("UserID");
    				On_UserID_Changed(oldValue, _userID);//\\
    			}
            }
        }
    	public static String UserID_PropertyName { get { return "UserID"; } }
        private Nullable<int> _userID;
        partial void On_UserID_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_UserID_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaTaiKhoan
        {
            get
            {
                return _maTaiKhoan;
            }
            set
            {
    			Nullable<int> oldValue =  _maTaiKhoan;
    			bool stopChanging = false;
                On_MaTaiKhoan_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaTaiKhoan");
    			if(!stopChanging)
    			{
    				_maTaiKhoan = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaTaiKhoan");
    				On_MaTaiKhoan_Changed(oldValue, _maTaiKhoan);//\\
    			}
            }
        }
    	public static String MaTaiKhoan_PropertyName { get { return "MaTaiKhoan"; } }
        private Nullable<int> _maTaiKhoan;
        partial void On_MaTaiKhoan_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaTaiKhoan_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<bool> KhoaSo
        {
            get
            {
                return _khoaSo;
            }
            set
            {
    			Nullable<bool> oldValue =  _khoaSo;
    			bool stopChanging = false;
                On_KhoaSo_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("KhoaSo");
    			if(!stopChanging)
    			{
    				_khoaSo = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("KhoaSo");
    				On_KhoaSo_Changed(oldValue, _khoaSo);//\\
    			}
            }
        }
    	public static String KhoaSo_PropertyName { get { return "KhoaSo"; } }
        private Nullable<bool> _khoaSo;
        partial void On_KhoaSo_Changing(Nullable<bool> currentValue, ref Nullable<bool> newValue, ref bool stopChanging);
        partial void On_KhoaSo_Changed(Nullable<bool> oldValue, Nullable<bool> currentValue);

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PSC_ERPModel", "FK_tblKhoaSo_MaTaiKhoan_tblKy", "tblKy")]
        public tblKy tblKy
        {//test
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblKy>("PSC_ERPModel.FK_tblKhoaSo_MaTaiKhoan_tblKy", "tblKy").Value;
            }
            set
            {
    			bool stopChanging = false;
    			On_tblKy_Changing(ref value, ref stopChanging);//\\//
    			if(!stopChanging)
    			{
    				((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblKy>("PSC_ERPModel.FK_tblKhoaSo_MaTaiKhoan_tblKy", "tblKy").Value = value;
    				On_tblKy_Changed(this.tblKy);//\\//
    			}
    	    }
        }
    	public static String tblKy_ReferencePropertyName { get { return "tblKy"; } }
    	partial void On_tblKy_Changing(ref tblKy newValue, ref bool stopChanging);
    	partial void On_tblKy_Changed(tblKy currentValue);
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblKy> tblKyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblKy>("PSC_ERPModel.FK_tblKhoaSo_MaTaiKhoan_tblKy", "tblKy");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblKy>("PSC_ERPModel.FK_tblKhoaSo_MaTaiKhoan_tblKy", "tblKy", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PSC_ERPModel", "FK_tblKhoaSo_MaTaiKhoan_tblTaiKhoan", "tblTaiKhoan")]
        public tblTaiKhoan tblTaiKhoan
        {//test
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTaiKhoan>("PSC_ERPModel.FK_tblKhoaSo_MaTaiKhoan_tblTaiKhoan", "tblTaiKhoan").Value;
            }
            set
            {
    			bool stopChanging = false;
    			On_tblTaiKhoan_Changing(ref value, ref stopChanging);//\\//
    			if(!stopChanging)
    			{
    				((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTaiKhoan>("PSC_ERPModel.FK_tblKhoaSo_MaTaiKhoan_tblTaiKhoan", "tblTaiKhoan").Value = value;
    				On_tblTaiKhoan_Changed(this.tblTaiKhoan);//\\//
    			}
    	    }
        }
    	public static String tblTaiKhoan_ReferencePropertyName { get { return "tblTaiKhoan"; } }
    	partial void On_tblTaiKhoan_Changing(ref tblTaiKhoan newValue, ref bool stopChanging);
    	partial void On_tblTaiKhoan_Changed(tblTaiKhoan currentValue);
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblTaiKhoan> tblTaiKhoanReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTaiKhoan>("PSC_ERPModel.FK_tblKhoaSo_MaTaiKhoan_tblTaiKhoan", "tblTaiKhoan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblTaiKhoan>("PSC_ERPModel.FK_tblKhoaSo_MaTaiKhoan_tblTaiKhoan", "tblTaiKhoan", value);
                }
            }
        }

        #endregion

    }
}
