//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi DESKTOP-J5VELTF\DELL luc 10:47:32 ngay 24/12/2021
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace PSC_ERP_Business.Main.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PSC_ERPModel", Name="tblLoaiHopDong")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblLoaiHopDong : PSC_ERP_Core.BaseEntityObject//EntityObject
    {
    	public tblLoaiHopDong()
    	{
    
    	}
        #region Factory Method
    
        /// <summary>
        /// Create a new tblLoaiHopDong object.
        /// </summary>
        /// <param name="maLoaiHopDong">Initial value of the MaLoaiHopDong property.</param>
        /// <param name="maQuanLy">Initial value of the MaQuanLy property.</param>
        /// <param name="tenLoaiHopDong">Initial value of the TenLoaiHopDong property.</param>
        public static tblLoaiHopDong CreatetblLoaiHopDong(int maLoaiHopDong, string maQuanLy, string tenLoaiHopDong)
        {
            tblLoaiHopDong tblLoaiHopDong = new tblLoaiHopDong();
            tblLoaiHopDong.MaLoaiHopDong = maLoaiHopDong;
            tblLoaiHopDong.MaQuanLy = maQuanLy;
            tblLoaiHopDong.TenLoaiHopDong = tenLoaiHopDong;
            return tblLoaiHopDong;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public int MaLoaiHopDong
        {
            get
            {
                return _maLoaiHopDong;
            }
            set
            {
                if (_maLoaiHopDong != value)
                {
        			int oldValue =  _maLoaiHopDong;
        			bool stopChanging = false;
                    On_MaLoaiHopDong_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("MaLoaiHopDong");
        			if(!stopChanging)
        			{
        				_maLoaiHopDong = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("MaLoaiHopDong");
        				On_MaLoaiHopDong_Changed(oldValue, _maLoaiHopDong);//\\
        			}
                }
            }
        }
    	public static String MaLoaiHopDong_PropertyName { get { return "MaLoaiHopDong"; } }
        private int _maLoaiHopDong;
        partial void On_MaLoaiHopDong_Changing(int currentValue, ref int newValue, ref bool stopChanging);
        partial void On_MaLoaiHopDong_Changed(int oldValue, int currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public string MaQuanLy
        {
            get
            {
                return _maQuanLy;
            }
            set
            {
    			string oldValue =  _maQuanLy;
    			bool stopChanging = false;
                On_MaQuanLy_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaQuanLy");
    			if(!stopChanging)
    			{
    				_maQuanLy = StructuralObject.SetValidValue(value, false);
    				ReportPropertyChanged("MaQuanLy");
    				On_MaQuanLy_Changed(oldValue, _maQuanLy);//\\
    			}
            }
        }
    	public static String MaQuanLy_PropertyName { get { return "MaQuanLy"; } }
        private string _maQuanLy;
        partial void On_MaQuanLy_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_MaQuanLy_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public string TenLoaiHopDong
        {
            get
            {
                return _tenLoaiHopDong;
            }
            set
            {
    			string oldValue =  _tenLoaiHopDong;
    			bool stopChanging = false;
                On_TenLoaiHopDong_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TenLoaiHopDong");
    			if(!stopChanging)
    			{
    				_tenLoaiHopDong = StructuralObject.SetValidValue(value, false);
    				ReportPropertyChanged("TenLoaiHopDong");
    				On_TenLoaiHopDong_Changed(oldValue, _tenLoaiHopDong);//\\
    			}
            }
        }
    	public static String TenLoaiHopDong_PropertyName { get { return "TenLoaiHopDong"; } }
        private string _tenLoaiHopDong;
        partial void On_TenLoaiHopDong_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenLoaiHopDong_Changed(string oldValue, string currentValue);

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PSC_ERPModel", "FK_tblHopDongMuaBan_tblLoaiHopDong", "tblHopDongMuaBan")]
        public EntityCollection<tblHopDongMuaBan> tblHopDongMuaBans
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblHopDongMuaBan>("PSC_ERPModel.FK_tblHopDongMuaBan_tblLoaiHopDong", "tblHopDongMuaBan");
            }
            set
            {
                if ((value != null))
                {
    				bool stopChanging = false;
    				On_tblHopDongMuaBans_Changing(ref value, ref stopChanging);//\\//
    				if(!stopChanging)
    				{
    					((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblHopDongMuaBan>("PSC_ERPModel.FK_tblHopDongMuaBan_tblLoaiHopDong", "tblHopDongMuaBan", value);
    					On_tblHopDongMuaBans_Changed(this.tblHopDongMuaBans);//\\//
    				}
    			}
            }
        }
    	public static String tblHopDongMuaBans_EntityCollectionPropertyName { get { return "tblHopDongMuaBans"; } }
    	partial void On_tblHopDongMuaBans_Changing(ref EntityCollection<tblHopDongMuaBan> newValue, ref bool stopChanging);
    	partial void On_tblHopDongMuaBans_Changed(EntityCollection<tblHopDongMuaBan> currentValue);

        #endregion

    }
}
