//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi DESKTOP-J5VELTF\DELL luc 10:47:32 ngay 24/12/2021
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace PSC_ERP_Business.Main.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PSC_ERPModel", Name="tblLoaiTien")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblLoaiTien : PSC_ERP_Core.BaseEntityObject//EntityObject
    {
    	public tblLoaiTien()
    	{
    
    	}
        #region Factory Method
    
        /// <summary>
        /// Create a new tblLoaiTien object.
        /// </summary>
        /// <param name="maLoaiTien">Initial value of the MaLoaiTien property.</param>
        /// <param name="tiGiaQuyDoi">Initial value of the TiGiaQuyDoi property.</param>
        /// <param name="tenLoaiTien">Initial value of the TenLoaiTien property.</param>
        /// <param name="maLoaiQuanLy">Initial value of the MaLoaiQuanLy property.</param>
        public static tblLoaiTien CreatetblLoaiTien(int maLoaiTien, double tiGiaQuyDoi, string tenLoaiTien, string maLoaiQuanLy)
        {
            tblLoaiTien tblLoaiTien = new tblLoaiTien();
            tblLoaiTien.MaLoaiTien = maLoaiTien;
            tblLoaiTien.TiGiaQuyDoi = tiGiaQuyDoi;
            tblLoaiTien.TenLoaiTien = tenLoaiTien;
            tblLoaiTien.MaLoaiQuanLy = maLoaiQuanLy;
            return tblLoaiTien;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public int MaLoaiTien
        {
            get
            {
                return _maLoaiTien;
            }
            set
            {
                if (_maLoaiTien != value)
                {
        			int oldValue =  _maLoaiTien;
        			bool stopChanging = false;
                    On_MaLoaiTien_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("MaLoaiTien");
        			if(!stopChanging)
        			{
        				_maLoaiTien = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("MaLoaiTien");
        				On_MaLoaiTien_Changed(oldValue, _maLoaiTien);//\\
        			}
                }
            }
        }
    	public static String MaLoaiTien_PropertyName { get { return "MaLoaiTien"; } }
        private int _maLoaiTien;
        partial void On_MaLoaiTien_Changing(int currentValue, ref int newValue, ref bool stopChanging);
        partial void On_MaLoaiTien_Changed(int oldValue, int currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public double TiGiaQuyDoi
        {
            get
            {
                return _tiGiaQuyDoi;
            }
            set
            {
    			double oldValue =  _tiGiaQuyDoi;
    			bool stopChanging = false;
                On_TiGiaQuyDoi_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TiGiaQuyDoi");
    			if(!stopChanging)
    			{
    				_tiGiaQuyDoi = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("TiGiaQuyDoi");
    				On_TiGiaQuyDoi_Changed(oldValue, _tiGiaQuyDoi);//\\
    			}
            }
        }
    	public static String TiGiaQuyDoi_PropertyName { get { return "TiGiaQuyDoi"; } }
        private double _tiGiaQuyDoi;
        partial void On_TiGiaQuyDoi_Changing(double currentValue, ref double newValue, ref bool stopChanging);
        partial void On_TiGiaQuyDoi_Changed(double oldValue, double currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public string TenLoaiTien
        {
            get
            {
                return _tenLoaiTien;
            }
            set
            {
    			string oldValue =  _tenLoaiTien;
    			bool stopChanging = false;
                On_TenLoaiTien_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TenLoaiTien");
    			if(!stopChanging)
    			{
    				_tenLoaiTien = StructuralObject.SetValidValue(value, false);
    				ReportPropertyChanged("TenLoaiTien");
    				On_TenLoaiTien_Changed(oldValue, _tenLoaiTien);//\\
    			}
            }
        }
    	public static String TenLoaiTien_PropertyName { get { return "TenLoaiTien"; } }
        private string _tenLoaiTien;
        partial void On_TenLoaiTien_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenLoaiTien_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public string MaLoaiQuanLy
        {
            get
            {
                return _maLoaiQuanLy;
            }
            set
            {
    			string oldValue =  _maLoaiQuanLy;
    			bool stopChanging = false;
                On_MaLoaiQuanLy_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaLoaiQuanLy");
    			if(!stopChanging)
    			{
    				_maLoaiQuanLy = StructuralObject.SetValidValue(value, false);
    				ReportPropertyChanged("MaLoaiQuanLy");
    				On_MaLoaiQuanLy_Changed(oldValue, _maLoaiQuanLy);//\\
    			}
            }
        }
    	public static String MaLoaiQuanLy_PropertyName { get { return "MaLoaiQuanLy"; } }
        private string _maLoaiQuanLy;
        partial void On_MaLoaiQuanLy_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_MaLoaiQuanLy_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string TienChan
        {
            get
            {
                return _tienChan;
            }
            set
            {
    			string oldValue =  _tienChan;
    			bool stopChanging = false;
                On_TienChan_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TienChan");
    			if(!stopChanging)
    			{
    				_tienChan = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("TienChan");
    				On_TienChan_Changed(oldValue, _tienChan);//\\
    			}
            }
        }
    	public static String TienChan_PropertyName { get { return "TienChan"; } }
        private string _tienChan;
        partial void On_TienChan_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TienChan_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string TienLe
        {
            get
            {
                return _tienLe;
            }
            set
            {
    			string oldValue =  _tienLe;
    			bool stopChanging = false;
                On_TienLe_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TienLe");
    			if(!stopChanging)
    			{
    				_tienLe = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("TienLe");
    				On_TienLe_Changed(oldValue, _tienLe);//\\
    			}
            }
        }
    	public static String TienLe_PropertyName { get { return "TienLe"; } }
        private string _tienLe;
        partial void On_TienLe_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TienLe_Changed(string oldValue, string currentValue);

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PSC_ERPModel", "FK_tblTienTe_tblLoaiTien", "tblTienTe")]
        public EntityCollection<tblTienTe> tblTienTes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblTienTe>("PSC_ERPModel.FK_tblTienTe_tblLoaiTien", "tblTienTe");
            }
            set
            {
                if ((value != null))
                {
    				bool stopChanging = false;
    				On_tblTienTes_Changing(ref value, ref stopChanging);//\\//
    				if(!stopChanging)
    				{
    					((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblTienTe>("PSC_ERPModel.FK_tblTienTe_tblLoaiTien", "tblTienTe", value);
    					On_tblTienTes_Changed(this.tblTienTes);//\\//
    				}
    			}
            }
        }
    	public static String tblTienTes_EntityCollectionPropertyName { get { return "tblTienTes"; } }
    	partial void On_tblTienTes_Changing(ref EntityCollection<tblTienTe> newValue, ref bool stopChanging);
    	partial void On_tblTienTes_Changed(EntityCollection<tblTienTe> currentValue);

        #endregion

    }
}
