//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi DESKTOP-J5VELTF\DELL luc 10:47:32 ngay 24/12/2021
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace PSC_ERP_Business.Main.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PSC_ERPModel", Name="tblnsNgoaiNgu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblnsNgoaiNgu : PSC_ERP_Core.BaseEntityObject//EntityObject
    {
    	public tblnsNgoaiNgu()
    	{
    
    	}
        #region Factory Method
    
        /// <summary>
        /// Create a new tblnsNgoaiNgu object.
        /// </summary>
        /// <param name="maNgoaiNgu">Initial value of the MaNgoaiNgu property.</param>
        /// <param name="maQuanLy">Initial value of the MaQuanLy property.</param>
        /// <param name="tenNgoaiNgu">Initial value of the TenNgoaiNgu property.</param>
        public static tblnsNgoaiNgu CreatetblnsNgoaiNgu(int maNgoaiNgu, string maQuanLy, string tenNgoaiNgu)
        {
            tblnsNgoaiNgu tblnsNgoaiNgu = new tblnsNgoaiNgu();
            tblnsNgoaiNgu.MaNgoaiNgu = maNgoaiNgu;
            tblnsNgoaiNgu.MaQuanLy = maQuanLy;
            tblnsNgoaiNgu.TenNgoaiNgu = tenNgoaiNgu;
            return tblnsNgoaiNgu;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public int MaNgoaiNgu
        {
            get
            {
                return _maNgoaiNgu;
            }
            set
            {
                if (_maNgoaiNgu != value)
                {
        			int oldValue =  _maNgoaiNgu;
        			bool stopChanging = false;
                    On_MaNgoaiNgu_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("MaNgoaiNgu");
        			if(!stopChanging)
        			{
        				_maNgoaiNgu = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("MaNgoaiNgu");
        				On_MaNgoaiNgu_Changed(oldValue, _maNgoaiNgu);//\\
        			}
                }
            }
        }
    	public static String MaNgoaiNgu_PropertyName { get { return "MaNgoaiNgu"; } }
        private int _maNgoaiNgu;
        partial void On_MaNgoaiNgu_Changing(int currentValue, ref int newValue, ref bool stopChanging);
        partial void On_MaNgoaiNgu_Changed(int oldValue, int currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public string MaQuanLy
        {
            get
            {
                return _maQuanLy;
            }
            set
            {
    			string oldValue =  _maQuanLy;
    			bool stopChanging = false;
                On_MaQuanLy_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaQuanLy");
    			if(!stopChanging)
    			{
    				_maQuanLy = StructuralObject.SetValidValue(value, false);
    				ReportPropertyChanged("MaQuanLy");
    				On_MaQuanLy_Changed(oldValue, _maQuanLy);//\\
    			}
            }
        }
    	public static String MaQuanLy_PropertyName { get { return "MaQuanLy"; } }
        private string _maQuanLy;
        partial void On_MaQuanLy_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_MaQuanLy_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public string TenNgoaiNgu
        {
            get
            {
                return _tenNgoaiNgu;
            }
            set
            {
    			string oldValue =  _tenNgoaiNgu;
    			bool stopChanging = false;
                On_TenNgoaiNgu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TenNgoaiNgu");
    			if(!stopChanging)
    			{
    				_tenNgoaiNgu = StructuralObject.SetValidValue(value, false);
    				ReportPropertyChanged("TenNgoaiNgu");
    				On_TenNgoaiNgu_Changed(oldValue, _tenNgoaiNgu);//\\
    			}
            }
        }
    	public static String TenNgoaiNgu_PropertyName { get { return "TenNgoaiNgu"; } }
        private string _tenNgoaiNgu;
        partial void On_TenNgoaiNgu_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenNgoaiNgu_Changed(string oldValue, string currentValue);

        #endregion

    }
}
