//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi DESKTOP-J5VELTF\DELL luc 10:47:32 ngay 24/12/2021
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace PSC_ERP_Business.Main.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PSC_ERPModel", Name="tblNghiemThuThanhLy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblNghiemThuThanhLy : PSC_ERP_Core.BaseEntityObject//EntityObject
    {
    	public tblNghiemThuThanhLy()
    	{
    
    	}
        #region Factory Method
    
        /// <summary>
        /// Create a new tblNghiemThuThanhLy object.
        /// </summary>
        /// <param name="maNghiemThuThanhLy">Initial value of the MaNghiemThuThanhLy property.</param>
        public static tblNghiemThuThanhLy CreatetblNghiemThuThanhLy(long maNghiemThuThanhLy)
        {
            tblNghiemThuThanhLy tblNghiemThuThanhLy = new tblNghiemThuThanhLy();
            tblNghiemThuThanhLy.MaNghiemThuThanhLy = maNghiemThuThanhLy;
            return tblNghiemThuThanhLy;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public long MaNghiemThuThanhLy
        {
            get
            {
                return _maNghiemThuThanhLy;
            }
            set
            {
                if (_maNghiemThuThanhLy != value)
                {
        			long oldValue =  _maNghiemThuThanhLy;
        			bool stopChanging = false;
                    On_MaNghiemThuThanhLy_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("MaNghiemThuThanhLy");
        			if(!stopChanging)
        			{
        				_maNghiemThuThanhLy = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("MaNghiemThuThanhLy");
        				On_MaNghiemThuThanhLy_Changed(oldValue, _maNghiemThuThanhLy);//\\
        			}
                }
            }
        }
    	public static String MaNghiemThuThanhLy_PropertyName { get { return "MaNghiemThuThanhLy"; } }
        private long _maNghiemThuThanhLy;
        partial void On_MaNghiemThuThanhLy_Changing(long currentValue, ref long newValue, ref bool stopChanging);
        partial void On_MaNghiemThuThanhLy_Changed(long oldValue, long currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string NoiDung
        {
            get
            {
                return _noiDung;
            }
            set
            {
    			string oldValue =  _noiDung;
    			bool stopChanging = false;
                On_NoiDung_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("NoiDung");
    			if(!stopChanging)
    			{
    				_noiDung = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("NoiDung");
    				On_NoiDung_Changed(oldValue, _noiDung);//\\
    			}
            }
        }
    	public static String NoiDung_PropertyName { get { return "NoiDung"; } }
        private string _noiDung;
        partial void On_NoiDung_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_NoiDung_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<long> MaHopDong
        {
            get
            {
                return _maHopDong;
            }
            set
            {
    			Nullable<long> oldValue =  _maHopDong;
    			bool stopChanging = false;
                On_MaHopDong_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaHopDong");
    			if(!stopChanging)
    			{
    				_maHopDong = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaHopDong");
    				On_MaHopDong_Changed(oldValue, _maHopDong);//\\
    			}
            }
        }
    	public static String MaHopDong_PropertyName { get { return "MaHopDong"; } }
        private Nullable<long> _maHopDong;
        partial void On_MaHopDong_Changing(Nullable<long> currentValue, ref Nullable<long> newValue, ref bool stopChanging);
        partial void On_MaHopDong_Changed(Nullable<long> oldValue, Nullable<long> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> NgayLap
        {
            get
            {
                return _ngayLap;
            }
            set
            {
    			Nullable<System.DateTime> oldValue =  _ngayLap;
    			bool stopChanging = false;
                On_NgayLap_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("NgayLap");
    			if(!stopChanging)
    			{
    				_ngayLap = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("NgayLap");
    				On_NgayLap_Changed(oldValue, _ngayLap);//\\
    			}
            }
        }
    	public static String NgayLap_PropertyName { get { return "NgayLap"; } }
        private Nullable<System.DateTime> _ngayLap;
        partial void On_NgayLap_Changing(Nullable<System.DateTime> currentValue, ref Nullable<System.DateTime> newValue, ref bool stopChanging);
        partial void On_NgayLap_Changed(Nullable<System.DateTime> oldValue, Nullable<System.DateTime> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<long> MaNguoiLap
        {
            get
            {
                return _maNguoiLap;
            }
            set
            {
    			Nullable<long> oldValue =  _maNguoiLap;
    			bool stopChanging = false;
                On_MaNguoiLap_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaNguoiLap");
    			if(!stopChanging)
    			{
    				_maNguoiLap = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaNguoiLap");
    				On_MaNguoiLap_Changed(oldValue, _maNguoiLap);//\\
    			}
            }
        }
    	public static String MaNguoiLap_PropertyName { get { return "MaNguoiLap"; } }
        private Nullable<long> _maNguoiLap;
        partial void On_MaNguoiLap_Changing(Nullable<long> currentValue, ref Nullable<long> newValue, ref bool stopChanging);
        partial void On_MaNguoiLap_Changed(Nullable<long> oldValue, Nullable<long> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<byte> TinhTrang
        {
            get
            {
                return _tinhTrang;
            }
            set
            {
    			Nullable<byte> oldValue =  _tinhTrang;
    			bool stopChanging = false;
                On_TinhTrang_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TinhTrang");
    			if(!stopChanging)
    			{
    				_tinhTrang = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("TinhTrang");
    				On_TinhTrang_Changed(oldValue, _tinhTrang);//\\
    			}
            }
        }
    	public static String TinhTrang_PropertyName { get { return "TinhTrang"; } }
        private Nullable<byte> _tinhTrang;
        partial void On_TinhTrang_Changing(Nullable<byte> currentValue, ref Nullable<byte> newValue, ref bool stopChanging);
        partial void On_TinhTrang_Changed(Nullable<byte> oldValue, Nullable<byte> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public byte[] FileDinhKem
        {
            get
            {
                return StructuralObject.GetValidValue(_fileDinhKem);
            }
            set
            {
    			byte[] oldValue =  _fileDinhKem;
    			bool stopChanging = false;
                On_FileDinhKem_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("FileDinhKem");
    			if(!stopChanging)
    			{
    				_fileDinhKem = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("FileDinhKem");
    				On_FileDinhKem_Changed(oldValue, _fileDinhKem);//\\
    			}
            }
        }
    	public static String FileDinhKem_PropertyName { get { return "FileDinhKem"; } }
        private byte[] _fileDinhKem;
        partial void On_FileDinhKem_Changing(byte[] currentValue, ref byte[] newValue, ref bool stopChanging);
        partial void On_FileDinhKem_Changed(byte[] oldValue, byte[] currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<long> MaNguoiKy
        {
            get
            {
                return _maNguoiKy;
            }
            set
            {
    			Nullable<long> oldValue =  _maNguoiKy;
    			bool stopChanging = false;
                On_MaNguoiKy_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaNguoiKy");
    			if(!stopChanging)
    			{
    				_maNguoiKy = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaNguoiKy");
    				On_MaNguoiKy_Changed(oldValue, _maNguoiKy);//\\
    			}
            }
        }
    	public static String MaNguoiKy_PropertyName { get { return "MaNguoiKy"; } }
        private Nullable<long> _maNguoiKy;
        partial void On_MaNguoiKy_Changing(Nullable<long> currentValue, ref Nullable<long> newValue, ref bool stopChanging);
        partial void On_MaNguoiKy_Changed(Nullable<long> oldValue, Nullable<long> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> NgayKy
        {
            get
            {
                return _ngayKy;
            }
            set
            {
    			Nullable<System.DateTime> oldValue =  _ngayKy;
    			bool stopChanging = false;
                On_NgayKy_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("NgayKy");
    			if(!stopChanging)
    			{
    				_ngayKy = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("NgayKy");
    				On_NgayKy_Changed(oldValue, _ngayKy);//\\
    			}
            }
        }
    	public static String NgayKy_PropertyName { get { return "NgayKy"; } }
        private Nullable<System.DateTime> _ngayKy;
        partial void On_NgayKy_Changing(Nullable<System.DateTime> currentValue, ref Nullable<System.DateTime> newValue, ref bool stopChanging);
        partial void On_NgayKy_Changed(Nullable<System.DateTime> oldValue, Nullable<System.DateTime> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string GhiChu
        {
            get
            {
                return _ghiChu;
            }
            set
            {
    			string oldValue =  _ghiChu;
    			bool stopChanging = false;
                On_GhiChu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("GhiChu");
    			if(!stopChanging)
    			{
    				_ghiChu = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("GhiChu");
    				On_GhiChu_Changed(oldValue, _ghiChu);//\\
    			}
            }
        }
    	public static String GhiChu_PropertyName { get { return "GhiChu"; } }
        private string _ghiChu;
        partial void On_GhiChu_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_GhiChu_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string TenNguoiKy
        {
            get
            {
                return _tenNguoiKy;
            }
            set
            {
    			string oldValue =  _tenNguoiKy;
    			bool stopChanging = false;
                On_TenNguoiKy_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TenNguoiKy");
    			if(!stopChanging)
    			{
    				_tenNguoiKy = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("TenNguoiKy");
    				On_TenNguoiKy_Changed(oldValue, _tenNguoiKy);//\\
    			}
            }
        }
    	public static String TenNguoiKy_PropertyName { get { return "TenNguoiKy"; } }
        private string _tenNguoiKy;
        partial void On_TenNguoiKy_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenNguoiKy_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> SoTien
        {
            get
            {
                return _soTien;
            }
            set
            {
    			Nullable<decimal> oldValue =  _soTien;
    			bool stopChanging = false;
                On_SoTien_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("SoTien");
    			if(!stopChanging)
    			{
    				_soTien = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("SoTien");
    				On_SoTien_Changed(oldValue, _soTien);//\\
    			}
            }
        }
    	public static String SoTien_PropertyName { get { return "SoTien"; } }
        private Nullable<decimal> _soTien;
        partial void On_SoTien_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_SoTien_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> Loai
        {
            get
            {
                return _loai;
            }
            set
            {
    			Nullable<int> oldValue =  _loai;
    			bool stopChanging = false;
                On_Loai_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("Loai");
    			if(!stopChanging)
    			{
    				_loai = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("Loai");
    				On_Loai_Changed(oldValue, _loai);//\\
    			}
            }
        }
    	public static String Loai_PropertyName { get { return "Loai"; } }
        private Nullable<int> _loai;
        partial void On_Loai_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_Loai_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string MaNghiemThuThanhLyQL
        {
            get
            {
                return _maNghiemThuThanhLyQL;
            }
            set
            {
    			string oldValue =  _maNghiemThuThanhLyQL;
    			bool stopChanging = false;
                On_MaNghiemThuThanhLyQL_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaNghiemThuThanhLyQL");
    			if(!stopChanging)
    			{
    				_maNghiemThuThanhLyQL = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("MaNghiemThuThanhLyQL");
    				On_MaNghiemThuThanhLyQL_Changed(oldValue, _maNghiemThuThanhLyQL);//\\
    			}
            }
        }
    	public static String MaNghiemThuThanhLyQL_PropertyName { get { return "MaNghiemThuThanhLyQL"; } }
        private string _maNghiemThuThanhLyQL;
        partial void On_MaNghiemThuThanhLyQL_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_MaNghiemThuThanhLyQL_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaLoaiTien
        {
            get
            {
                return _maLoaiTien;
            }
            set
            {
    			Nullable<int> oldValue =  _maLoaiTien;
    			bool stopChanging = false;
                On_MaLoaiTien_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaLoaiTien");
    			if(!stopChanging)
    			{
    				_maLoaiTien = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaLoaiTien");
    				On_MaLoaiTien_Changed(oldValue, _maLoaiTien);//\\
    			}
            }
        }
    	public static String MaLoaiTien_PropertyName { get { return "MaLoaiTien"; } }
        private Nullable<int> _maLoaiTien;
        partial void On_MaLoaiTien_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaLoaiTien_Changed(Nullable<int> oldValue, Nullable<int> currentValue);

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PSC_ERPModel", "FK_tblNghiemThuThanhLy_tblHopDongMuaBan", "tblHopDongMuaBan")]
        public tblHopDongMuaBan tblHopDongMuaBan
        {//test
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblHopDongMuaBan>("PSC_ERPModel.FK_tblNghiemThuThanhLy_tblHopDongMuaBan", "tblHopDongMuaBan").Value;
            }
            set
            {
    			bool stopChanging = false;
    			On_tblHopDongMuaBan_Changing(ref value, ref stopChanging);//\\//
    			if(!stopChanging)
    			{
    				((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblHopDongMuaBan>("PSC_ERPModel.FK_tblNghiemThuThanhLy_tblHopDongMuaBan", "tblHopDongMuaBan").Value = value;
    				On_tblHopDongMuaBan_Changed(this.tblHopDongMuaBan);//\\//
    			}
    	    }
        }
    	public static String tblHopDongMuaBan_ReferencePropertyName { get { return "tblHopDongMuaBan"; } }
    	partial void On_tblHopDongMuaBan_Changing(ref tblHopDongMuaBan newValue, ref bool stopChanging);
    	partial void On_tblHopDongMuaBan_Changed(tblHopDongMuaBan currentValue);
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblHopDongMuaBan> tblHopDongMuaBanReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblHopDongMuaBan>("PSC_ERPModel.FK_tblNghiemThuThanhLy_tblHopDongMuaBan", "tblHopDongMuaBan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblHopDongMuaBan>("PSC_ERPModel.FK_tblNghiemThuThanhLy_tblHopDongMuaBan", "tblHopDongMuaBan", value);
                }
            }
        }

        #endregion

    }
}
