//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi DESKTOP-J5VELTF\DELL luc 10:47:32 ngay 24/12/2021
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace PSC_ERP_Business.Main.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PSC_ERPModel", Name="tblnsTonGiao")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblnsTonGiao : PSC_ERP_Core.BaseEntityObject//EntityObject
    {
    	public tblnsTonGiao()
    	{
    
    	}
        #region Factory Method
    
        /// <summary>
        /// Create a new tblnsTonGiao object.
        /// </summary>
        /// <param name="maTonGiao">Initial value of the MaTonGiao property.</param>
        /// <param name="maQuanLy">Initial value of the MaQuanLy property.</param>
        /// <param name="tenTonGiao">Initial value of the TenTonGiao property.</param>
        public static tblnsTonGiao CreatetblnsTonGiao(int maTonGiao, string maQuanLy, string tenTonGiao)
        {
            tblnsTonGiao tblnsTonGiao = new tblnsTonGiao();
            tblnsTonGiao.MaTonGiao = maTonGiao;
            tblnsTonGiao.MaQuanLy = maQuanLy;
            tblnsTonGiao.TenTonGiao = tenTonGiao;
            return tblnsTonGiao;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public int MaTonGiao
        {
            get
            {
                return _maTonGiao;
            }
            set
            {
                if (_maTonGiao != value)
                {
        			int oldValue =  _maTonGiao;
        			bool stopChanging = false;
                    On_MaTonGiao_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("MaTonGiao");
        			if(!stopChanging)
        			{
        				_maTonGiao = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("MaTonGiao");
        				On_MaTonGiao_Changed(oldValue, _maTonGiao);//\\
        			}
                }
            }
        }
    	public static String MaTonGiao_PropertyName { get { return "MaTonGiao"; } }
        private int _maTonGiao;
        partial void On_MaTonGiao_Changing(int currentValue, ref int newValue, ref bool stopChanging);
        partial void On_MaTonGiao_Changed(int oldValue, int currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public string MaQuanLy
        {
            get
            {
                return _maQuanLy;
            }
            set
            {
    			string oldValue =  _maQuanLy;
    			bool stopChanging = false;
                On_MaQuanLy_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaQuanLy");
    			if(!stopChanging)
    			{
    				_maQuanLy = StructuralObject.SetValidValue(value, false);
    				ReportPropertyChanged("MaQuanLy");
    				On_MaQuanLy_Changed(oldValue, _maQuanLy);//\\
    			}
            }
        }
    	public static String MaQuanLy_PropertyName { get { return "MaQuanLy"; } }
        private string _maQuanLy;
        partial void On_MaQuanLy_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_MaQuanLy_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public string TenTonGiao
        {
            get
            {
                return _tenTonGiao;
            }
            set
            {
    			string oldValue =  _tenTonGiao;
    			bool stopChanging = false;
                On_TenTonGiao_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TenTonGiao");
    			if(!stopChanging)
    			{
    				_tenTonGiao = StructuralObject.SetValidValue(value, false);
    				ReportPropertyChanged("TenTonGiao");
    				On_TenTonGiao_Changed(oldValue, _tenTonGiao);//\\
    			}
            }
        }
    	public static String TenTonGiao_PropertyName { get { return "TenTonGiao"; } }
        private string _tenTonGiao;
        partial void On_TenTonGiao_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenTonGiao_Changed(string oldValue, string currentValue);

        #endregion

    }
}
