//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi DESKTOP-J5VELTF\DELL luc 10:47:32 ngay 24/12/2021
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace PSC_ERP_Business.Main.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PSC_ERPModel", Name="tblPhanBoChiPhiCCDCChuyenTuTaiSan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblPhanBoChiPhiCCDCChuyenTuTaiSan : PSC_ERP_Core.BaseEntityObject//EntityObject
    {
    	public tblPhanBoChiPhiCCDCChuyenTuTaiSan()
    	{
    
    	}
        #region Factory Method
    
        /// <summary>
        /// Create a new tblPhanBoChiPhiCCDCChuyenTuTaiSan object.
        /// </summary>
        /// <param name="maPhanBo">Initial value of the MaPhanBo property.</param>
        public static tblPhanBoChiPhiCCDCChuyenTuTaiSan CreatetblPhanBoChiPhiCCDCChuyenTuTaiSan(int maPhanBo)
        {
            tblPhanBoChiPhiCCDCChuyenTuTaiSan tblPhanBoChiPhiCCDCChuyenTuTaiSan = new tblPhanBoChiPhiCCDCChuyenTuTaiSan();
            tblPhanBoChiPhiCCDCChuyenTuTaiSan.MaPhanBo = maPhanBo;
            return tblPhanBoChiPhiCCDCChuyenTuTaiSan;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public int MaPhanBo
        {
            get
            {
                return _maPhanBo;
            }
            set
            {
                if (_maPhanBo != value)
                {
        			int oldValue =  _maPhanBo;
        			bool stopChanging = false;
                    On_MaPhanBo_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("MaPhanBo");
        			if(!stopChanging)
        			{
        				_maPhanBo = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("MaPhanBo");
        				On_MaPhanBo_Changed(oldValue, _maPhanBo);//\\
        			}
                }
            }
        }
    	public static String MaPhanBo_PropertyName { get { return "MaPhanBo"; } }
        private int _maPhanBo;
        partial void On_MaPhanBo_Changing(int currentValue, ref int newValue, ref bool stopChanging);
        partial void On_MaPhanBo_Changed(int oldValue, int currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string SoChungTu
        {
            get
            {
                return _soChungTu;
            }
            set
            {
    			string oldValue =  _soChungTu;
    			bool stopChanging = false;
                On_SoChungTu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("SoChungTu");
    			if(!stopChanging)
    			{
    				_soChungTu = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("SoChungTu");
    				On_SoChungTu_Changed(oldValue, _soChungTu);//\\
    			}
            }
        }
    	public static String SoChungTu_PropertyName { get { return "SoChungTu"; } }
        private string _soChungTu;
        partial void On_SoChungTu_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_SoChungTu_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> NgayChungTu
        {
            get
            {
                return _ngayChungTu;
            }
            set
            {
    			Nullable<System.DateTime> oldValue =  _ngayChungTu;
    			bool stopChanging = false;
                On_NgayChungTu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("NgayChungTu");
    			if(!stopChanging)
    			{
    				_ngayChungTu = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("NgayChungTu");
    				On_NgayChungTu_Changed(oldValue, _ngayChungTu);//\\
    			}
            }
        }
    	public static String NgayChungTu_PropertyName { get { return "NgayChungTu"; } }
        private Nullable<System.DateTime> _ngayChungTu;
        partial void On_NgayChungTu_Changing(Nullable<System.DateTime> currentValue, ref Nullable<System.DateTime> newValue, ref bool stopChanging);
        partial void On_NgayChungTu_Changed(Nullable<System.DateTime> oldValue, Nullable<System.DateTime> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> PhanTramPhanBo
        {
            get
            {
                return _phanTramPhanBo;
            }
            set
            {
    			Nullable<decimal> oldValue =  _phanTramPhanBo;
    			bool stopChanging = false;
                On_PhanTramPhanBo_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("PhanTramPhanBo");
    			if(!stopChanging)
    			{
    				_phanTramPhanBo = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("PhanTramPhanBo");
    				On_PhanTramPhanBo_Changed(oldValue, _phanTramPhanBo);//\\
    			}
            }
        }
    	public static String PhanTramPhanBo_PropertyName { get { return "PhanTramPhanBo"; } }
        private Nullable<decimal> _phanTramPhanBo;
        partial void On_PhanTramPhanBo_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_PhanTramPhanBo_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string DienGiai
        {
            get
            {
                return _dienGiai;
            }
            set
            {
    			string oldValue =  _dienGiai;
    			bool stopChanging = false;
                On_DienGiai_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("DienGiai");
    			if(!stopChanging)
    			{
    				_dienGiai = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("DienGiai");
    				On_DienGiai_Changed(oldValue, _dienGiai);//\\
    			}
            }
        }
    	public static String DienGiai_PropertyName { get { return "DienGiai"; } }
        private string _dienGiai;
        partial void On_DienGiai_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_DienGiai_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaUserLap
        {
            get
            {
                return _maUserLap;
            }
            set
            {
    			Nullable<int> oldValue =  _maUserLap;
    			bool stopChanging = false;
                On_MaUserLap_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaUserLap");
    			if(!stopChanging)
    			{
    				_maUserLap = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaUserLap");
    				On_MaUserLap_Changed(oldValue, _maUserLap);//\\
    			}
            }
        }
    	public static String MaUserLap_PropertyName { get { return "MaUserLap"; } }
        private Nullable<int> _maUserLap;
        partial void On_MaUserLap_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaUserLap_Changed(Nullable<int> oldValue, Nullable<int> currentValue);

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PSC_ERPModel", "FK_tblCT_PhanBoChiPhiCCDCChuyenTuTaiSan_tblPhanBoChiPhiCCDCChuyenTuTaiSan", "tblCT_PhanBoChiPhiCCDCChuyenTuTaiSan")]
        public EntityCollection<tblCT_PhanBoChiPhiCCDCChuyenTuTaiSan> tblCT_PhanBoChiPhiCCDCChuyenTuTaiSan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblCT_PhanBoChiPhiCCDCChuyenTuTaiSan>("PSC_ERPModel.FK_tblCT_PhanBoChiPhiCCDCChuyenTuTaiSan_tblPhanBoChiPhiCCDCChuyenTuTaiSan", "tblCT_PhanBoChiPhiCCDCChuyenTuTaiSan");
            }
            set
            {
                if ((value != null))
                {
    				bool stopChanging = false;
    				On_tblCT_PhanBoChiPhiCCDCChuyenTuTaiSan_Changing(ref value, ref stopChanging);//\\//
    				if(!stopChanging)
    				{
    					((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblCT_PhanBoChiPhiCCDCChuyenTuTaiSan>("PSC_ERPModel.FK_tblCT_PhanBoChiPhiCCDCChuyenTuTaiSan_tblPhanBoChiPhiCCDCChuyenTuTaiSan", "tblCT_PhanBoChiPhiCCDCChuyenTuTaiSan", value);
    					On_tblCT_PhanBoChiPhiCCDCChuyenTuTaiSan_Changed(this.tblCT_PhanBoChiPhiCCDCChuyenTuTaiSan);//\\//
    				}
    			}
            }
        }
    	public static String tblCT_PhanBoChiPhiCCDCChuyenTuTaiSan_EntityCollectionPropertyName { get { return "tblCT_PhanBoChiPhiCCDCChuyenTuTaiSan"; } }
    	partial void On_tblCT_PhanBoChiPhiCCDCChuyenTuTaiSan_Changing(ref EntityCollection<tblCT_PhanBoChiPhiCCDCChuyenTuTaiSan> newValue, ref bool stopChanging);
    	partial void On_tblCT_PhanBoChiPhiCCDCChuyenTuTaiSan_Changed(EntityCollection<tblCT_PhanBoChiPhiCCDCChuyenTuTaiSan> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PSC_ERPModel", "FK_tblPhanBoChiPhiCCDCChuyenTuTaiSan_app_users", "app_users")]
        public app_users app_users
        {//test
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<app_users>("PSC_ERPModel.FK_tblPhanBoChiPhiCCDCChuyenTuTaiSan_app_users", "app_users").Value;
            }
            set
            {
    			bool stopChanging = false;
    			On_app_users_Changing(ref value, ref stopChanging);//\\//
    			if(!stopChanging)
    			{
    				((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<app_users>("PSC_ERPModel.FK_tblPhanBoChiPhiCCDCChuyenTuTaiSan_app_users", "app_users").Value = value;
    				On_app_users_Changed(this.app_users);//\\//
    			}
    	    }
        }
    	public static String app_users_ReferencePropertyName { get { return "app_users"; } }
    	partial void On_app_users_Changing(ref app_users newValue, ref bool stopChanging);
    	partial void On_app_users_Changed(app_users currentValue);
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<app_users> app_usersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<app_users>("PSC_ERPModel.FK_tblPhanBoChiPhiCCDCChuyenTuTaiSan_app_users", "app_users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<app_users>("PSC_ERPModel.FK_tblPhanBoChiPhiCCDCChuyenTuTaiSan_app_users", "app_users", value);
                }
            }
        }

        #endregion

    }
}
