//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi DESKTOP-J5VELTF\DELL luc 10:47:32 ngay 24/12/2021
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace PSC_ERP_Business.Main.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PSC_ERPModel", Name="tblTinhThanh")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblTinhThanh : PSC_ERP_Core.BaseEntityObject//EntityObject
    {
    	public tblTinhThanh()
    	{
    
    	}
        #region Factory Method
    
        /// <summary>
        /// Create a new tblTinhThanh object.
        /// </summary>
        /// <param name="maTinhThanh">Initial value of the MaTinhThanh property.</param>
        public static tblTinhThanh CreatetblTinhThanh(int maTinhThanh)
        {
            tblTinhThanh tblTinhThanh = new tblTinhThanh();
            tblTinhThanh.MaTinhThanh = maTinhThanh;
            return tblTinhThanh;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public int MaTinhThanh
        {
            get
            {
                return _maTinhThanh;
            }
            set
            {
                if (_maTinhThanh != value)
                {
        			int oldValue =  _maTinhThanh;
        			bool stopChanging = false;
                    On_MaTinhThanh_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("MaTinhThanh");
        			if(!stopChanging)
        			{
        				_maTinhThanh = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("MaTinhThanh");
        				On_MaTinhThanh_Changed(oldValue, _maTinhThanh);//\\
        			}
                }
            }
        }
    	public static String MaTinhThanh_PropertyName { get { return "MaTinhThanh"; } }
        private int _maTinhThanh;
        partial void On_MaTinhThanh_Changing(int currentValue, ref int newValue, ref bool stopChanging);
        partial void On_MaTinhThanh_Changed(int oldValue, int currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string MaTinhThanhQuanLy
        {
            get
            {
                return _maTinhThanhQuanLy;
            }
            set
            {
    			string oldValue =  _maTinhThanhQuanLy;
    			bool stopChanging = false;
                On_MaTinhThanhQuanLy_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaTinhThanhQuanLy");
    			if(!stopChanging)
    			{
    				_maTinhThanhQuanLy = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("MaTinhThanhQuanLy");
    				On_MaTinhThanhQuanLy_Changed(oldValue, _maTinhThanhQuanLy);//\\
    			}
            }
        }
    	public static String MaTinhThanhQuanLy_PropertyName { get { return "MaTinhThanhQuanLy"; } }
        private string _maTinhThanhQuanLy;
        partial void On_MaTinhThanhQuanLy_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_MaTinhThanhQuanLy_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string TenTinhThanh
        {
            get
            {
                return _tenTinhThanh;
            }
            set
            {
    			string oldValue =  _tenTinhThanh;
    			bool stopChanging = false;
                On_TenTinhThanh_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TenTinhThanh");
    			if(!stopChanging)
    			{
    				_tenTinhThanh = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("TenTinhThanh");
    				On_TenTinhThanh_Changed(oldValue, _tenTinhThanh);//\\
    			}
            }
        }
    	public static String TenTinhThanh_PropertyName { get { return "TenTinhThanh"; } }
        private string _tenTinhThanh;
        partial void On_TenTinhThanh_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenTinhThanh_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string DienGiai
        {
            get
            {
                return _dienGiai;
            }
            set
            {
    			string oldValue =  _dienGiai;
    			bool stopChanging = false;
                On_DienGiai_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("DienGiai");
    			if(!stopChanging)
    			{
    				_dienGiai = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("DienGiai");
    				On_DienGiai_Changed(oldValue, _dienGiai);//\\
    			}
            }
        }
    	public static String DienGiai_PropertyName { get { return "DienGiai"; } }
        private string _dienGiai;
        partial void On_DienGiai_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_DienGiai_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaKhuVuc
        {
            get
            {
                return _maKhuVuc;
            }
            set
            {
    			Nullable<int> oldValue =  _maKhuVuc;
    			bool stopChanging = false;
                On_MaKhuVuc_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaKhuVuc");
    			if(!stopChanging)
    			{
    				_maKhuVuc = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaKhuVuc");
    				On_MaKhuVuc_Changed(oldValue, _maKhuVuc);//\\
    			}
            }
        }
    	public static String MaKhuVuc_PropertyName { get { return "MaKhuVuc"; } }
        private Nullable<int> _maKhuVuc;
        partial void On_MaKhuVuc_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaKhuVuc_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaQuocGia
        {
            get
            {
                return _maQuocGia;
            }
            set
            {
    			Nullable<int> oldValue =  _maQuocGia;
    			bool stopChanging = false;
                On_MaQuocGia_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaQuocGia");
    			if(!stopChanging)
    			{
    				_maQuocGia = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaQuocGia");
    				On_MaQuocGia_Changed(oldValue, _maQuocGia);//\\
    			}
            }
        }
    	public static String MaQuocGia_PropertyName { get { return "MaQuocGia"; } }
        private Nullable<int> _maQuocGia;
        partial void On_MaQuocGia_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaQuocGia_Changed(Nullable<int> oldValue, Nullable<int> currentValue);

        #endregion

    }
}
