//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi DESKTOP-J5VELTF\DELL luc 10:47:32 ngay 24/12/2021
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace PSC_ERP_Business.Main.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PSC_ERPModel", Name="v_BaoCaoTieuMuc")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class v_BaoCaoTieuMuc : PSC_ERP_Core.BaseEntityObject//EntityObject
    {
    	public v_BaoCaoTieuMuc()
    	{
    
    	}
        #region Factory Method
    
        /// <summary>
        /// Create a new v_BaoCaoTieuMuc object.
        /// </summary>
        /// <param name="soChungTu">Initial value of the SoChungTu property.</param>
        /// <param name="maTieuMuc">Initial value of the MaTieuMuc property.</param>
        public static v_BaoCaoTieuMuc Createv_BaoCaoTieuMuc(string soChungTu, string maTieuMuc)
        {
            v_BaoCaoTieuMuc v_BaoCaoTieuMuc = new v_BaoCaoTieuMuc();
            v_BaoCaoTieuMuc.SoChungTu = soChungTu;
            v_BaoCaoTieuMuc.MaTieuMuc = maTieuMuc;
            return v_BaoCaoTieuMuc;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public string SoChungTu
        {
            get
            {
                return _soChungTu;
            }
            set
            {
                if (_soChungTu != value)
                {
        			string oldValue =  _soChungTu;
        			bool stopChanging = false;
                    On_SoChungTu_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("SoChungTu");
        			if(!stopChanging)
        			{
        				_soChungTu = StructuralObject.SetValidValue(value, false);
        				ReportPropertyChanged("SoChungTu");
        				On_SoChungTu_Changed(oldValue, _soChungTu);//\\
        			}
                }
            }
        }
    	public static String SoChungTu_PropertyName { get { return "SoChungTu"; } }
        private string _soChungTu;
        partial void On_SoChungTu_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_SoChungTu_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> NgayLap
        {
            get
            {
                return _ngayLap;
            }
            set
            {
    			Nullable<System.DateTime> oldValue =  _ngayLap;
    			bool stopChanging = false;
                On_NgayLap_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("NgayLap");
    			if(!stopChanging)
    			{
    				_ngayLap = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("NgayLap");
    				On_NgayLap_Changed(oldValue, _ngayLap);//\\
    			}
            }
        }
    	public static String NgayLap_PropertyName { get { return "NgayLap"; } }
        private Nullable<System.DateTime> _ngayLap;
        partial void On_NgayLap_Changing(Nullable<System.DateTime> currentValue, ref Nullable<System.DateTime> newValue, ref bool stopChanging);
        partial void On_NgayLap_Changed(Nullable<System.DateTime> oldValue, Nullable<System.DateTime> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string DienGiai
        {
            get
            {
                return _dienGiai;
            }
            set
            {
    			string oldValue =  _dienGiai;
    			bool stopChanging = false;
                On_DienGiai_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("DienGiai");
    			if(!stopChanging)
    			{
    				_dienGiai = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("DienGiai");
    				On_DienGiai_Changed(oldValue, _dienGiai);//\\
    			}
            }
        }
    	public static String DienGiai_PropertyName { get { return "DienGiai"; } }
        private string _dienGiai;
        partial void On_DienGiai_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_DienGiai_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public string MaTieuMuc
        {
            get
            {
                return _maTieuMuc;
            }
            set
            {
                if (_maTieuMuc != value)
                {
        			string oldValue =  _maTieuMuc;
        			bool stopChanging = false;
                    On_MaTieuMuc_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("MaTieuMuc");
        			if(!stopChanging)
        			{
        				_maTieuMuc = StructuralObject.SetValidValue(value, false);
        				ReportPropertyChanged("MaTieuMuc");
        				On_MaTieuMuc_Changed(oldValue, _maTieuMuc);//\\
        			}
                }
            }
        }
    	public static String MaTieuMuc_PropertyName { get { return "MaTieuMuc"; } }
        private string _maTieuMuc;
        partial void On_MaTieuMuc_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_MaTieuMuc_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> SoTien
        {
            get
            {
                return _soTien;
            }
            set
            {
    			Nullable<decimal> oldValue =  _soTien;
    			bool stopChanging = false;
                On_SoTien_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("SoTien");
    			if(!stopChanging)
    			{
    				_soTien = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("SoTien");
    				On_SoTien_Changed(oldValue, _soTien);//\\
    			}
            }
        }
    	public static String SoTien_PropertyName { get { return "SoTien"; } }
        private Nullable<decimal> _soTien;
        partial void On_SoTien_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_SoTien_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);

        #endregion

    }
}
