//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi DESKTOP-J5VELTF\DELL luc 10:47:32 ngay 24/12/2021
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace PSC_ERP_Business.Main.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PSC_ERPModel", Name="V_BoPhan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class V_BoPhan : PSC_ERP_Core.BaseEntityObject//EntityObject
    {
    	public V_BoPhan()
    	{
    
    	}
        #region Factory Method
    
        /// <summary>
        /// Create a new V_BoPhan object.
        /// </summary>
        /// <param name="maBoPhanCon">Initial value of the MaBoPhanCon property.</param>
        public static V_BoPhan CreateV_BoPhan(int maBoPhanCon)
        {
            V_BoPhan v_BoPhan = new V_BoPhan();
            v_BoPhan.MaBoPhanCon = maBoPhanCon;
            return v_BoPhan;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public int MaBoPhanCon
        {
            get
            {
                return _maBoPhanCon;
            }
            set
            {
                if (_maBoPhanCon != value)
                {
        			int oldValue =  _maBoPhanCon;
        			bool stopChanging = false;
                    On_MaBoPhanCon_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("MaBoPhanCon");
        			if(!stopChanging)
        			{
        				_maBoPhanCon = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("MaBoPhanCon");
        				On_MaBoPhanCon_Changed(oldValue, _maBoPhanCon);//\\
        			}
                }
            }
        }
    	public static String MaBoPhanCon_PropertyName { get { return "MaBoPhanCon"; } }
        private int _maBoPhanCon;
        partial void On_MaBoPhanCon_Changing(int currentValue, ref int newValue, ref bool stopChanging);
        partial void On_MaBoPhanCon_Changed(int oldValue, int currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string TenBoPhanCon
        {
            get
            {
                return _tenBoPhanCon;
            }
            set
            {
    			string oldValue =  _tenBoPhanCon;
    			bool stopChanging = false;
                On_TenBoPhanCon_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TenBoPhanCon");
    			if(!stopChanging)
    			{
    				_tenBoPhanCon = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("TenBoPhanCon");
    				On_TenBoPhanCon_Changed(oldValue, _tenBoPhanCon);//\\
    			}
            }
        }
    	public static String TenBoPhanCon_PropertyName { get { return "TenBoPhanCon"; } }
        private string _tenBoPhanCon;
        partial void On_TenBoPhanCon_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenBoPhanCon_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaBoPhanCha
        {
            get
            {
                return _maBoPhanCha;
            }
            set
            {
    			Nullable<int> oldValue =  _maBoPhanCha;
    			bool stopChanging = false;
                On_MaBoPhanCha_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaBoPhanCha");
    			if(!stopChanging)
    			{
    				_maBoPhanCha = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaBoPhanCha");
    				On_MaBoPhanCha_Changed(oldValue, _maBoPhanCha);//\\
    			}
            }
        }
    	public static String MaBoPhanCha_PropertyName { get { return "MaBoPhanCha"; } }
        private Nullable<int> _maBoPhanCha;
        partial void On_MaBoPhanCha_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaBoPhanCha_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string TenBoPhanCha
        {
            get
            {
                return _tenBoPhanCha;
            }
            set
            {
    			string oldValue =  _tenBoPhanCha;
    			bool stopChanging = false;
                On_TenBoPhanCha_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TenBoPhanCha");
    			if(!stopChanging)
    			{
    				_tenBoPhanCha = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("TenBoPhanCha");
    				On_TenBoPhanCha_Changed(oldValue, _tenBoPhanCha);//\\
    			}
            }
        }
    	public static String TenBoPhanCha_PropertyName { get { return "TenBoPhanCha"; } }
        private string _tenBoPhanCha;
        partial void On_TenBoPhanCha_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenBoPhanCha_Changed(string oldValue, string currentValue);

        #endregion

    }
}
