//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi DESKTOP-J5VELTF\DELL luc 10:47:32 ngay 24/12/2021
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace PSC_ERP_Business.Main.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PSC_ERPModel", Name="v_DSNhanVienSaiLuong")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class v_DSNhanVienSaiLuong : PSC_ERP_Core.BaseEntityObject//EntityObject
    {
    	public v_DSNhanVienSaiLuong()
    	{
    
    	}
        #region Factory Method
    
        /// <summary>
        /// Create a new v_DSNhanVienSaiLuong object.
        /// </summary>
        /// <param name="maNhanVien">Initial value of the MaNhanVien property.</param>
        /// <param name="maQLNhanVien">Initial value of the MaQLNhanVien property.</param>
        public static v_DSNhanVienSaiLuong Createv_DSNhanVienSaiLuong(long maNhanVien, string maQLNhanVien)
        {
            v_DSNhanVienSaiLuong v_DSNhanVienSaiLuong = new v_DSNhanVienSaiLuong();
            v_DSNhanVienSaiLuong.MaNhanVien = maNhanVien;
            v_DSNhanVienSaiLuong.MaQLNhanVien = maQLNhanVien;
            return v_DSNhanVienSaiLuong;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public long MaNhanVien
        {
            get
            {
                return _maNhanVien;
            }
            set
            {
                if (_maNhanVien != value)
                {
        			long oldValue =  _maNhanVien;
        			bool stopChanging = false;
                    On_MaNhanVien_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("MaNhanVien");
        			if(!stopChanging)
        			{
        				_maNhanVien = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("MaNhanVien");
        				On_MaNhanVien_Changed(oldValue, _maNhanVien);//\\
        			}
                }
            }
        }
    	public static String MaNhanVien_PropertyName { get { return "MaNhanVien"; } }
        private long _maNhanVien;
        partial void On_MaNhanVien_Changing(long currentValue, ref long newValue, ref bool stopChanging);
        partial void On_MaNhanVien_Changed(long oldValue, long currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public string MaQLNhanVien
        {
            get
            {
                return _maQLNhanVien;
            }
            set
            {
                if (_maQLNhanVien != value)
                {
        			string oldValue =  _maQLNhanVien;
        			bool stopChanging = false;
                    On_MaQLNhanVien_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("MaQLNhanVien");
        			if(!stopChanging)
        			{
        				_maQLNhanVien = StructuralObject.SetValidValue(value, false);
        				ReportPropertyChanged("MaQLNhanVien");
        				On_MaQLNhanVien_Changed(oldValue, _maQLNhanVien);//\\
        			}
                }
            }
        }
    	public static String MaQLNhanVien_PropertyName { get { return "MaQLNhanVien"; } }
        private string _maQLNhanVien;
        partial void On_MaQLNhanVien_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_MaQLNhanVien_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string TenNhanVien
        {
            get
            {
                return _tenNhanVien;
            }
            set
            {
    			string oldValue =  _tenNhanVien;
    			bool stopChanging = false;
                On_TenNhanVien_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TenNhanVien");
    			if(!stopChanging)
    			{
    				_tenNhanVien = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("TenNhanVien");
    				On_TenNhanVien_Changed(oldValue, _tenNhanVien);//\\
    			}
            }
        }
    	public static String TenNhanVien_PropertyName { get { return "TenNhanVien"; } }
        private string _tenNhanVien;
        partial void On_TenNhanVien_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenNhanVien_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string CMND
        {
            get
            {
                return _cMND;
            }
            set
            {
    			string oldValue =  _cMND;
    			bool stopChanging = false;
                On_CMND_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("CMND");
    			if(!stopChanging)
    			{
    				_cMND = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("CMND");
    				On_CMND_Changed(oldValue, _cMND);//\\
    			}
            }
        }
    	public static String CMND_PropertyName { get { return "CMND"; } }
        private string _cMND;
        partial void On_CMND_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_CMND_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string TenBoPhan
        {
            get
            {
                return _tenBoPhan;
            }
            set
            {
    			string oldValue =  _tenBoPhan;
    			bool stopChanging = false;
                On_TenBoPhan_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TenBoPhan");
    			if(!stopChanging)
    			{
    				_tenBoPhan = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("TenBoPhan");
    				On_TenBoPhan_Changed(oldValue, _tenBoPhan);//\\
    			}
            }
        }
    	public static String TenBoPhan_PropertyName { get { return "TenBoPhan"; } }
        private string _tenBoPhan;
        partial void On_TenBoPhan_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenBoPhan_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> HeSoLuongNoiBo
        {
            get
            {
                return _heSoLuongNoiBo;
            }
            set
            {
    			Nullable<decimal> oldValue =  _heSoLuongNoiBo;
    			bool stopChanging = false;
                On_HeSoLuongNoiBo_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("HeSoLuongNoiBo");
    			if(!stopChanging)
    			{
    				_heSoLuongNoiBo = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("HeSoLuongNoiBo");
    				On_HeSoLuongNoiBo_Changed(oldValue, _heSoLuongNoiBo);//\\
    			}
            }
        }
    	public static String HeSoLuongNoiBo_PropertyName { get { return "HeSoLuongNoiBo"; } }
        private Nullable<decimal> _heSoLuongNoiBo;
        partial void On_HeSoLuongNoiBo_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_HeSoLuongNoiBo_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> HeSoLuong
        {
            get
            {
                return _heSoLuong;
            }
            set
            {
    			Nullable<decimal> oldValue =  _heSoLuong;
    			bool stopChanging = false;
                On_HeSoLuong_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("HeSoLuong");
    			if(!stopChanging)
    			{
    				_heSoLuong = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("HeSoLuong");
    				On_HeSoLuong_Changed(oldValue, _heSoLuong);//\\
    			}
            }
        }
    	public static String HeSoLuong_PropertyName { get { return "HeSoLuong"; } }
        private Nullable<decimal> _heSoLuong;
        partial void On_HeSoLuong_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_HeSoLuong_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> HeSoBu
        {
            get
            {
                return _heSoBu;
            }
            set
            {
    			Nullable<decimal> oldValue =  _heSoBu;
    			bool stopChanging = false;
                On_HeSoBu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("HeSoBu");
    			if(!stopChanging)
    			{
    				_heSoBu = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("HeSoBu");
    				On_HeSoBu_Changed(oldValue, _heSoBu);//\\
    			}
            }
        }
    	public static String HeSoBu_PropertyName { get { return "HeSoBu"; } }
        private Nullable<decimal> _heSoBu;
        partial void On_HeSoBu_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_HeSoBu_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> HeSoDocHai
        {
            get
            {
                return _heSoDocHai;
            }
            set
            {
    			Nullable<decimal> oldValue =  _heSoDocHai;
    			bool stopChanging = false;
                On_HeSoDocHai_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("HeSoDocHai");
    			if(!stopChanging)
    			{
    				_heSoDocHai = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("HeSoDocHai");
    				On_HeSoDocHai_Changed(oldValue, _heSoDocHai);//\\
    			}
            }
        }
    	public static String HeSoDocHai_PropertyName { get { return "HeSoDocHai"; } }
        private Nullable<decimal> _heSoDocHai;
        partial void On_HeSoDocHai_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_HeSoDocHai_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> HeSoPhuCapChucVu
        {
            get
            {
                return _heSoPhuCapChucVu;
            }
            set
            {
    			Nullable<decimal> oldValue =  _heSoPhuCapChucVu;
    			bool stopChanging = false;
                On_HeSoPhuCapChucVu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("HeSoPhuCapChucVu");
    			if(!stopChanging)
    			{
    				_heSoPhuCapChucVu = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("HeSoPhuCapChucVu");
    				On_HeSoPhuCapChucVu_Changed(oldValue, _heSoPhuCapChucVu);//\\
    			}
            }
        }
    	public static String HeSoPhuCapChucVu_PropertyName { get { return "HeSoPhuCapChucVu"; } }
        private Nullable<decimal> _heSoPhuCapChucVu;
        partial void On_HeSoPhuCapChucVu_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_HeSoPhuCapChucVu_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> HeSoVuotKhung
        {
            get
            {
                return _heSoVuotKhung;
            }
            set
            {
    			Nullable<decimal> oldValue =  _heSoVuotKhung;
    			bool stopChanging = false;
                On_HeSoVuotKhung_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("HeSoVuotKhung");
    			if(!stopChanging)
    			{
    				_heSoVuotKhung = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("HeSoVuotKhung");
    				On_HeSoVuotKhung_Changed(oldValue, _heSoVuotKhung);//\\
    			}
            }
        }
    	public static String HeSoVuotKhung_PropertyName { get { return "HeSoVuotKhung"; } }
        private Nullable<decimal> _heSoVuotKhung;
        partial void On_HeSoVuotKhung_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_HeSoVuotKhung_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);

        #endregion

    }
}
