//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi DESKTOP-J5VELTF\DELL luc 10:47:32 ngay 24/12/2021
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace PSC_ERP_Business.Main.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PSC_ERPModel", Name="V_GetMaxMocThoiGian_QuyetDinhNangLuong")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class V_GetMaxMocThoiGian_QuyetDinhNangLuong : PSC_ERP_Core.BaseEntityObject//EntityObject
    {
    	public V_GetMaxMocThoiGian_QuyetDinhNangLuong()
    	{
    
    	}
        #region Factory Method
    
        /// <summary>
        /// Create a new V_GetMaxMocThoiGian_QuyetDinhNangLuong object.
        /// </summary>
        /// <param name="maQuyetDinh">Initial value of the MaQuyetDinh property.</param>
        /// <param name="soQuyetDinh">Initial value of the SoQuyetDinh property.</param>
        /// <param name="maNhanVien">Initial value of the MaNhanVien property.</param>
        public static V_GetMaxMocThoiGian_QuyetDinhNangLuong CreateV_GetMaxMocThoiGian_QuyetDinhNangLuong(int maQuyetDinh, string soQuyetDinh, long maNhanVien)
        {
            V_GetMaxMocThoiGian_QuyetDinhNangLuong v_GetMaxMocThoiGian_QuyetDinhNangLuong = new V_GetMaxMocThoiGian_QuyetDinhNangLuong();
            v_GetMaxMocThoiGian_QuyetDinhNangLuong.MaQuyetDinh = maQuyetDinh;
            v_GetMaxMocThoiGian_QuyetDinhNangLuong.SoQuyetDinh = soQuyetDinh;
            v_GetMaxMocThoiGian_QuyetDinhNangLuong.MaNhanVien = maNhanVien;
            return v_GetMaxMocThoiGian_QuyetDinhNangLuong;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public int MaQuyetDinh
        {
            get
            {
                return _maQuyetDinh;
            }
            set
            {
                if (_maQuyetDinh != value)
                {
        			int oldValue =  _maQuyetDinh;
        			bool stopChanging = false;
                    On_MaQuyetDinh_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("MaQuyetDinh");
        			if(!stopChanging)
        			{
        				_maQuyetDinh = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("MaQuyetDinh");
        				On_MaQuyetDinh_Changed(oldValue, _maQuyetDinh);//\\
        			}
                }
            }
        }
    	public static String MaQuyetDinh_PropertyName { get { return "MaQuyetDinh"; } }
        private int _maQuyetDinh;
        partial void On_MaQuyetDinh_Changing(int currentValue, ref int newValue, ref bool stopChanging);
        partial void On_MaQuyetDinh_Changed(int oldValue, int currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public string SoQuyetDinh
        {
            get
            {
                return _soQuyetDinh;
            }
            set
            {
                if (_soQuyetDinh != value)
                {
        			string oldValue =  _soQuyetDinh;
        			bool stopChanging = false;
                    On_SoQuyetDinh_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("SoQuyetDinh");
        			if(!stopChanging)
        			{
        				_soQuyetDinh = StructuralObject.SetValidValue(value, false);
        				ReportPropertyChanged("SoQuyetDinh");
        				On_SoQuyetDinh_Changed(oldValue, _soQuyetDinh);//\\
        			}
                }
            }
        }
    	public static String SoQuyetDinh_PropertyName { get { return "SoQuyetDinh"; } }
        private string _soQuyetDinh;
        partial void On_SoQuyetDinh_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_SoQuyetDinh_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public long MaNhanVien
        {
            get
            {
                return _maNhanVien;
            }
            set
            {
                if (_maNhanVien != value)
                {
        			long oldValue =  _maNhanVien;
        			bool stopChanging = false;
                    On_MaNhanVien_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("MaNhanVien");
        			if(!stopChanging)
        			{
        				_maNhanVien = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("MaNhanVien");
        				On_MaNhanVien_Changed(oldValue, _maNhanVien);//\\
        			}
                }
            }
        }
    	public static String MaNhanVien_PropertyName { get { return "MaNhanVien"; } }
        private long _maNhanVien;
        partial void On_MaNhanVien_Changing(long currentValue, ref long newValue, ref bool stopChanging);
        partial void On_MaNhanVien_Changed(long oldValue, long currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaChucVu
        {
            get
            {
                return _maChucVu;
            }
            set
            {
    			Nullable<int> oldValue =  _maChucVu;
    			bool stopChanging = false;
                On_MaChucVu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaChucVu");
    			if(!stopChanging)
    			{
    				_maChucVu = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaChucVu");
    				On_MaChucVu_Changed(oldValue, _maChucVu);//\\
    			}
            }
        }
    	public static String MaChucVu_PropertyName { get { return "MaChucVu"; } }
        private Nullable<int> _maChucVu;
        partial void On_MaChucVu_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaChucVu_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string TenChucVu
        {
            get
            {
                return _tenChucVu;
            }
            set
            {
    			string oldValue =  _tenChucVu;
    			bool stopChanging = false;
                On_TenChucVu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TenChucVu");
    			if(!stopChanging)
    			{
    				_tenChucVu = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("TenChucVu");
    				On_TenChucVu_Changed(oldValue, _tenChucVu);//\\
    			}
            }
        }
    	public static String TenChucVu_PropertyName { get { return "TenChucVu"; } }
        private string _tenChucVu;
        partial void On_TenChucVu_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenChucVu_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaBoPhan
        {
            get
            {
                return _maBoPhan;
            }
            set
            {
    			Nullable<int> oldValue =  _maBoPhan;
    			bool stopChanging = false;
                On_MaBoPhan_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaBoPhan");
    			if(!stopChanging)
    			{
    				_maBoPhan = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaBoPhan");
    				On_MaBoPhan_Changed(oldValue, _maBoPhan);//\\
    			}
            }
        }
    	public static String MaBoPhan_PropertyName { get { return "MaBoPhan"; } }
        private Nullable<int> _maBoPhan;
        partial void On_MaBoPhan_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaBoPhan_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string TenBoPhan
        {
            get
            {
                return _tenBoPhan;
            }
            set
            {
    			string oldValue =  _tenBoPhan;
    			bool stopChanging = false;
                On_TenBoPhan_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TenBoPhan");
    			if(!stopChanging)
    			{
    				_tenBoPhan = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("TenBoPhan");
    				On_TenBoPhan_Changed(oldValue, _tenBoPhan);//\\
    			}
            }
        }
    	public static String TenBoPhan_PropertyName { get { return "TenBoPhan"; } }
        private string _tenBoPhan;
        partial void On_TenBoPhan_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenBoPhan_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string MaQLNhanVien
        {
            get
            {
                return _maQLNhanVien;
            }
            set
            {
    			string oldValue =  _maQLNhanVien;
    			bool stopChanging = false;
                On_MaQLNhanVien_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaQLNhanVien");
    			if(!stopChanging)
    			{
    				_maQLNhanVien = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("MaQLNhanVien");
    				On_MaQLNhanVien_Changed(oldValue, _maQLNhanVien);//\\
    			}
            }
        }
    	public static String MaQLNhanVien_PropertyName { get { return "MaQLNhanVien"; } }
        private string _maQLNhanVien;
        partial void On_MaQLNhanVien_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_MaQLNhanVien_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaNhomBaoHiemNgach
        {
            get
            {
                return _maNhomBaoHiemNgach;
            }
            set
            {
    			Nullable<int> oldValue =  _maNhomBaoHiemNgach;
    			bool stopChanging = false;
                On_MaNhomBaoHiemNgach_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaNhomBaoHiemNgach");
    			if(!stopChanging)
    			{
    				_maNhomBaoHiemNgach = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaNhomBaoHiemNgach");
    				On_MaNhomBaoHiemNgach_Changed(oldValue, _maNhomBaoHiemNgach);//\\
    			}
            }
        }
    	public static String MaNhomBaoHiemNgach_PropertyName { get { return "MaNhomBaoHiemNgach"; } }
        private Nullable<int> _maNhomBaoHiemNgach;
        partial void On_MaNhomBaoHiemNgach_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaNhomBaoHiemNgach_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaNgachBaoHiemCu
        {
            get
            {
                return _maNgachBaoHiemCu;
            }
            set
            {
    			Nullable<int> oldValue =  _maNgachBaoHiemCu;
    			bool stopChanging = false;
                On_MaNgachBaoHiemCu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaNgachBaoHiemCu");
    			if(!stopChanging)
    			{
    				_maNgachBaoHiemCu = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaNgachBaoHiemCu");
    				On_MaNgachBaoHiemCu_Changed(oldValue, _maNgachBaoHiemCu);//\\
    			}
            }
        }
    	public static String MaNgachBaoHiemCu_PropertyName { get { return "MaNgachBaoHiemCu"; } }
        private Nullable<int> _maNgachBaoHiemCu;
        partial void On_MaNgachBaoHiemCu_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaNgachBaoHiemCu_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string TenNgachBaoHiemCu
        {
            get
            {
                return _tenNgachBaoHiemCu;
            }
            set
            {
    			string oldValue =  _tenNgachBaoHiemCu;
    			bool stopChanging = false;
                On_TenNgachBaoHiemCu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TenNgachBaoHiemCu");
    			if(!stopChanging)
    			{
    				_tenNgachBaoHiemCu = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("TenNgachBaoHiemCu");
    				On_TenNgachBaoHiemCu_Changed(oldValue, _tenNgachBaoHiemCu);//\\
    			}
            }
        }
    	public static String TenNgachBaoHiemCu_PropertyName { get { return "TenNgachBaoHiemCu"; } }
        private string _tenNgachBaoHiemCu;
        partial void On_TenNgachBaoHiemCu_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenNgachBaoHiemCu_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string TenBacBaoHiemCu
        {
            get
            {
                return _tenBacBaoHiemCu;
            }
            set
            {
    			string oldValue =  _tenBacBaoHiemCu;
    			bool stopChanging = false;
                On_TenBacBaoHiemCu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TenBacBaoHiemCu");
    			if(!stopChanging)
    			{
    				_tenBacBaoHiemCu = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("TenBacBaoHiemCu");
    				On_TenBacBaoHiemCu_Changed(oldValue, _tenBacBaoHiemCu);//\\
    			}
            }
        }
    	public static String TenBacBaoHiemCu_PropertyName { get { return "TenBacBaoHiemCu"; } }
        private string _tenBacBaoHiemCu;
        partial void On_TenBacBaoHiemCu_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenBacBaoHiemCu_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaNgachBaoHiemMoi
        {
            get
            {
                return _maNgachBaoHiemMoi;
            }
            set
            {
    			Nullable<int> oldValue =  _maNgachBaoHiemMoi;
    			bool stopChanging = false;
                On_MaNgachBaoHiemMoi_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaNgachBaoHiemMoi");
    			if(!stopChanging)
    			{
    				_maNgachBaoHiemMoi = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaNgachBaoHiemMoi");
    				On_MaNgachBaoHiemMoi_Changed(oldValue, _maNgachBaoHiemMoi);//\\
    			}
            }
        }
    	public static String MaNgachBaoHiemMoi_PropertyName { get { return "MaNgachBaoHiemMoi"; } }
        private Nullable<int> _maNgachBaoHiemMoi;
        partial void On_MaNgachBaoHiemMoi_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaNgachBaoHiemMoi_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string TenNgachBaoHiemMoi
        {
            get
            {
                return _tenNgachBaoHiemMoi;
            }
            set
            {
    			string oldValue =  _tenNgachBaoHiemMoi;
    			bool stopChanging = false;
                On_TenNgachBaoHiemMoi_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TenNgachBaoHiemMoi");
    			if(!stopChanging)
    			{
    				_tenNgachBaoHiemMoi = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("TenNgachBaoHiemMoi");
    				On_TenNgachBaoHiemMoi_Changed(oldValue, _tenNgachBaoHiemMoi);//\\
    			}
            }
        }
    	public static String TenNgachBaoHiemMoi_PropertyName { get { return "TenNgachBaoHiemMoi"; } }
        private string _tenNgachBaoHiemMoi;
        partial void On_TenNgachBaoHiemMoi_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenNgachBaoHiemMoi_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string TenBacBaoHiemMoi
        {
            get
            {
                return _tenBacBaoHiemMoi;
            }
            set
            {
    			string oldValue =  _tenBacBaoHiemMoi;
    			bool stopChanging = false;
                On_TenBacBaoHiemMoi_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TenBacBaoHiemMoi");
    			if(!stopChanging)
    			{
    				_tenBacBaoHiemMoi = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("TenBacBaoHiemMoi");
    				On_TenBacBaoHiemMoi_Changed(oldValue, _tenBacBaoHiemMoi);//\\
    			}
            }
        }
    	public static String TenBacBaoHiemMoi_PropertyName { get { return "TenBacBaoHiemMoi"; } }
        private string _tenBacBaoHiemMoi;
        partial void On_TenBacBaoHiemMoi_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenBacBaoHiemMoi_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> NgayHieuLuc
        {
            get
            {
                return _ngayHieuLuc;
            }
            set
            {
    			Nullable<System.DateTime> oldValue =  _ngayHieuLuc;
    			bool stopChanging = false;
                On_NgayHieuLuc_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("NgayHieuLuc");
    			if(!stopChanging)
    			{
    				_ngayHieuLuc = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("NgayHieuLuc");
    				On_NgayHieuLuc_Changed(oldValue, _ngayHieuLuc);//\\
    			}
            }
        }
    	public static String NgayHieuLuc_PropertyName { get { return "NgayHieuLuc"; } }
        private Nullable<System.DateTime> _ngayHieuLuc;
        partial void On_NgayHieuLuc_Changing(Nullable<System.DateTime> currentValue, ref Nullable<System.DateTime> newValue, ref bool stopChanging);
        partial void On_NgayHieuLuc_Changed(Nullable<System.DateTime> oldValue, Nullable<System.DateTime> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> MocThoiGianNangBac
        {
            get
            {
                return _mocThoiGianNangBac;
            }
            set
            {
    			Nullable<System.DateTime> oldValue =  _mocThoiGianNangBac;
    			bool stopChanging = false;
                On_MocThoiGianNangBac_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MocThoiGianNangBac");
    			if(!stopChanging)
    			{
    				_mocThoiGianNangBac = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MocThoiGianNangBac");
    				On_MocThoiGianNangBac_Changed(oldValue, _mocThoiGianNangBac);//\\
    			}
            }
        }
    	public static String MocThoiGianNangBac_PropertyName { get { return "MocThoiGianNangBac"; } }
        private Nullable<System.DateTime> _mocThoiGianNangBac;
        partial void On_MocThoiGianNangBac_Changing(Nullable<System.DateTime> currentValue, ref Nullable<System.DateTime> newValue, ref bool stopChanging);
        partial void On_MocThoiGianNangBac_Changed(Nullable<System.DateTime> oldValue, Nullable<System.DateTime> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<long> MaNguoiLap
        {
            get
            {
                return _maNguoiLap;
            }
            set
            {
    			Nullable<long> oldValue =  _maNguoiLap;
    			bool stopChanging = false;
                On_MaNguoiLap_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaNguoiLap");
    			if(!stopChanging)
    			{
    				_maNguoiLap = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaNguoiLap");
    				On_MaNguoiLap_Changed(oldValue, _maNguoiLap);//\\
    			}
            }
        }
    	public static String MaNguoiLap_PropertyName { get { return "MaNguoiLap"; } }
        private Nullable<long> _maNguoiLap;
        partial void On_MaNguoiLap_Changing(Nullable<long> currentValue, ref Nullable<long> newValue, ref bool stopChanging);
        partial void On_MaNguoiLap_Changed(Nullable<long> oldValue, Nullable<long> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> NgayLap
        {
            get
            {
                return _ngayLap;
            }
            set
            {
    			Nullable<System.DateTime> oldValue =  _ngayLap;
    			bool stopChanging = false;
                On_NgayLap_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("NgayLap");
    			if(!stopChanging)
    			{
    				_ngayLap = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("NgayLap");
    				On_NgayLap_Changed(oldValue, _ngayLap);//\\
    			}
            }
        }
    	public static String NgayLap_PropertyName { get { return "NgayLap"; } }
        private Nullable<System.DateTime> _ngayLap;
        partial void On_NgayLap_Changing(Nullable<System.DateTime> currentValue, ref Nullable<System.DateTime> newValue, ref bool stopChanging);
        partial void On_NgayLap_Changed(Nullable<System.DateTime> oldValue, Nullable<System.DateTime> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> KyTinhLuongApDung
        {
            get
            {
                return _kyTinhLuongApDung;
            }
            set
            {
    			Nullable<int> oldValue =  _kyTinhLuongApDung;
    			bool stopChanging = false;
                On_KyTinhLuongApDung_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("KyTinhLuongApDung");
    			if(!stopChanging)
    			{
    				_kyTinhLuongApDung = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("KyTinhLuongApDung");
    				On_KyTinhLuongApDung_Changed(oldValue, _kyTinhLuongApDung);//\\
    			}
            }
        }
    	public static String KyTinhLuongApDung_PropertyName { get { return "KyTinhLuongApDung"; } }
        private Nullable<int> _kyTinhLuongApDung;
        partial void On_KyTinhLuongApDung_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_KyTinhLuongApDung_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> TuKy
        {
            get
            {
                return _tuKy;
            }
            set
            {
    			Nullable<System.DateTime> oldValue =  _tuKy;
    			bool stopChanging = false;
                On_TuKy_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TuKy");
    			if(!stopChanging)
    			{
    				_tuKy = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("TuKy");
    				On_TuKy_Changed(oldValue, _tuKy);//\\
    			}
            }
        }
    	public static String TuKy_PropertyName { get { return "TuKy"; } }
        private Nullable<System.DateTime> _tuKy;
        partial void On_TuKy_Changing(Nullable<System.DateTime> currentValue, ref Nullable<System.DateTime> newValue, ref bool stopChanging);
        partial void On_TuKy_Changed(Nullable<System.DateTime> oldValue, Nullable<System.DateTime> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> DenKy
        {
            get
            {
                return _denKy;
            }
            set
            {
    			Nullable<System.DateTime> oldValue =  _denKy;
    			bool stopChanging = false;
                On_DenKy_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("DenKy");
    			if(!stopChanging)
    			{
    				_denKy = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("DenKy");
    				On_DenKy_Changed(oldValue, _denKy);//\\
    			}
            }
        }
    	public static String DenKy_PropertyName { get { return "DenKy"; } }
        private Nullable<System.DateTime> _denKy;
        partial void On_DenKy_Changing(Nullable<System.DateTime> currentValue, ref Nullable<System.DateTime> newValue, ref bool stopChanging);
        partial void On_DenKy_Changed(Nullable<System.DateTime> oldValue, Nullable<System.DateTime> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> SoKy
        {
            get
            {
                return _soKy;
            }
            set
            {
    			Nullable<int> oldValue =  _soKy;
    			bool stopChanging = false;
                On_SoKy_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("SoKy");
    			if(!stopChanging)
    			{
    				_soKy = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("SoKy");
    				On_SoKy_Changed(oldValue, _soKy);//\\
    			}
            }
        }
    	public static String SoKy_PropertyName { get { return "SoKy"; } }
        private Nullable<int> _soKy;
        partial void On_SoKy_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_SoKy_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> HSPCCu
        {
            get
            {
                return _hSPCCu;
            }
            set
            {
    			Nullable<decimal> oldValue =  _hSPCCu;
    			bool stopChanging = false;
                On_HSPCCu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("HSPCCu");
    			if(!stopChanging)
    			{
    				_hSPCCu = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("HSPCCu");
    				On_HSPCCu_Changed(oldValue, _hSPCCu);//\\
    			}
            }
        }
    	public static String HSPCCu_PropertyName { get { return "HSPCCu"; } }
        private Nullable<decimal> _hSPCCu;
        partial void On_HSPCCu_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_HSPCCu_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> HSPCMoi
        {
            get
            {
                return _hSPCMoi;
            }
            set
            {
    			Nullable<decimal> oldValue =  _hSPCMoi;
    			bool stopChanging = false;
                On_HSPCMoi_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("HSPCMoi");
    			if(!stopChanging)
    			{
    				_hSPCMoi = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("HSPCMoi");
    				On_HSPCMoi_Changed(oldValue, _hSPCMoi);//\\
    			}
            }
        }
    	public static String HSPCMoi_PropertyName { get { return "HSPCMoi"; } }
        private Nullable<decimal> _hSPCMoi;
        partial void On_HSPCMoi_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_HSPCMoi_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> HSVKCu
        {
            get
            {
                return _hSVKCu;
            }
            set
            {
    			Nullable<decimal> oldValue =  _hSVKCu;
    			bool stopChanging = false;
                On_HSVKCu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("HSVKCu");
    			if(!stopChanging)
    			{
    				_hSVKCu = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("HSVKCu");
    				On_HSVKCu_Changed(oldValue, _hSVKCu);//\\
    			}
            }
        }
    	public static String HSVKCu_PropertyName { get { return "HSVKCu"; } }
        private Nullable<decimal> _hSVKCu;
        partial void On_HSVKCu_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_HSVKCu_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> HSVKMoi
        {
            get
            {
                return _hSVKMoi;
            }
            set
            {
    			Nullable<decimal> oldValue =  _hSVKMoi;
    			bool stopChanging = false;
                On_HSVKMoi_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("HSVKMoi");
    			if(!stopChanging)
    			{
    				_hSVKMoi = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("HSVKMoi");
    				On_HSVKMoi_Changed(oldValue, _hSVKMoi);//\\
    			}
            }
        }
    	public static String HSVKMoi_PropertyName { get { return "HSVKMoi"; } }
        private Nullable<decimal> _hSVKMoi;
        partial void On_HSVKMoi_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_HSVKMoi_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> ChenhLechHeSo
        {
            get
            {
                return _chenhLechHeSo;
            }
            set
            {
    			Nullable<decimal> oldValue =  _chenhLechHeSo;
    			bool stopChanging = false;
                On_ChenhLechHeSo_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("ChenhLechHeSo");
    			if(!stopChanging)
    			{
    				_chenhLechHeSo = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("ChenhLechHeSo");
    				On_ChenhLechHeSo_Changed(oldValue, _chenhLechHeSo);//\\
    			}
            }
        }
    	public static String ChenhLechHeSo_PropertyName { get { return "ChenhLechHeSo"; } }
        private Nullable<decimal> _chenhLechHeSo;
        partial void On_ChenhLechHeSo_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_ChenhLechHeSo_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> LuongDot1
        {
            get
            {
                return _luongDot1;
            }
            set
            {
    			Nullable<decimal> oldValue =  _luongDot1;
    			bool stopChanging = false;
                On_LuongDot1_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("LuongDot1");
    			if(!stopChanging)
    			{
    				_luongDot1 = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("LuongDot1");
    				On_LuongDot1_Changed(oldValue, _luongDot1);//\\
    			}
            }
        }
    	public static String LuongDot1_PropertyName { get { return "LuongDot1"; } }
        private Nullable<decimal> _luongDot1;
        partial void On_LuongDot1_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_LuongDot1_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> LuongDot2
        {
            get
            {
                return _luongDot2;
            }
            set
            {
    			Nullable<decimal> oldValue =  _luongDot2;
    			bool stopChanging = false;
                On_LuongDot2_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("LuongDot2");
    			if(!stopChanging)
    			{
    				_luongDot2 = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("LuongDot2");
    				On_LuongDot2_Changed(oldValue, _luongDot2);//\\
    			}
            }
        }
    	public static String LuongDot2_PropertyName { get { return "LuongDot2"; } }
        private Nullable<decimal> _luongDot2;
        partial void On_LuongDot2_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_LuongDot2_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> BHXH
        {
            get
            {
                return _bHXH;
            }
            set
            {
    			Nullable<decimal> oldValue =  _bHXH;
    			bool stopChanging = false;
                On_BHXH_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("BHXH");
    			if(!stopChanging)
    			{
    				_bHXH = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("BHXH");
    				On_BHXH_Changed(oldValue, _bHXH);//\\
    			}
            }
        }
    	public static String BHXH_PropertyName { get { return "BHXH"; } }
        private Nullable<decimal> _bHXH;
        partial void On_BHXH_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_BHXH_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> ConLai
        {
            get
            {
                return _conLai;
            }
            set
            {
    			Nullable<decimal> oldValue =  _conLai;
    			bool stopChanging = false;
                On_ConLai_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("ConLai");
    			if(!stopChanging)
    			{
    				_conLai = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("ConLai");
    				On_ConLai_Changed(oldValue, _conLai);//\\
    			}
            }
        }
    	public static String ConLai_PropertyName { get { return "ConLai"; } }
        private Nullable<decimal> _conLai;
        partial void On_ConLai_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_ConLai_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> MocThoiGianNangBacMoi
        {
            get
            {
                return _mocThoiGianNangBacMoi;
            }
            set
            {
    			Nullable<System.DateTime> oldValue =  _mocThoiGianNangBacMoi;
    			bool stopChanging = false;
                On_MocThoiGianNangBacMoi_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MocThoiGianNangBacMoi");
    			if(!stopChanging)
    			{
    				_mocThoiGianNangBacMoi = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MocThoiGianNangBacMoi");
    				On_MocThoiGianNangBacMoi_Changed(oldValue, _mocThoiGianNangBacMoi);//\\
    			}
            }
        }
    	public static String MocThoiGianNangBacMoi_PropertyName { get { return "MocThoiGianNangBacMoi"; } }
        private Nullable<System.DateTime> _mocThoiGianNangBacMoi;
        partial void On_MocThoiGianNangBacMoi_Changing(Nullable<System.DateTime> currentValue, ref Nullable<System.DateTime> newValue, ref bool stopChanging);
        partial void On_MocThoiGianNangBacMoi_Changed(Nullable<System.DateTime> oldValue, Nullable<System.DateTime> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> NgayDenHan
        {
            get
            {
                return _ngayDenHan;
            }
            set
            {
    			Nullable<System.DateTime> oldValue =  _ngayDenHan;
    			bool stopChanging = false;
                On_NgayDenHan_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("NgayDenHan");
    			if(!stopChanging)
    			{
    				_ngayDenHan = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("NgayDenHan");
    				On_NgayDenHan_Changed(oldValue, _ngayDenHan);//\\
    			}
            }
        }
    	public static String NgayDenHan_PropertyName { get { return "NgayDenHan"; } }
        private Nullable<System.DateTime> _ngayDenHan;
        partial void On_NgayDenHan_Changing(Nullable<System.DateTime> currentValue, ref Nullable<System.DateTime> newValue, ref bool stopChanging);
        partial void On_NgayDenHan_Changed(Nullable<System.DateTime> oldValue, Nullable<System.DateTime> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> NgayDenHanMoi
        {
            get
            {
                return _ngayDenHanMoi;
            }
            set
            {
    			Nullable<System.DateTime> oldValue =  _ngayDenHanMoi;
    			bool stopChanging = false;
                On_NgayDenHanMoi_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("NgayDenHanMoi");
    			if(!stopChanging)
    			{
    				_ngayDenHanMoi = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("NgayDenHanMoi");
    				On_NgayDenHanMoi_Changed(oldValue, _ngayDenHanMoi);//\\
    			}
            }
        }
    	public static String NgayDenHanMoi_PropertyName { get { return "NgayDenHanMoi"; } }
        private Nullable<System.DateTime> _ngayDenHanMoi;
        partial void On_NgayDenHanMoi_Changing(Nullable<System.DateTime> currentValue, ref Nullable<System.DateTime> newValue, ref bool stopChanging);
        partial void On_NgayDenHanMoi_Changed(Nullable<System.DateTime> oldValue, Nullable<System.DateTime> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> ThoiGiaNangBacCu
        {
            get
            {
                return _thoiGiaNangBacCu;
            }
            set
            {
    			Nullable<int> oldValue =  _thoiGiaNangBacCu;
    			bool stopChanging = false;
                On_ThoiGiaNangBacCu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("ThoiGiaNangBacCu");
    			if(!stopChanging)
    			{
    				_thoiGiaNangBacCu = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("ThoiGiaNangBacCu");
    				On_ThoiGiaNangBacCu_Changed(oldValue, _thoiGiaNangBacCu);//\\
    			}
            }
        }
    	public static String ThoiGiaNangBacCu_PropertyName { get { return "ThoiGiaNangBacCu"; } }
        private Nullable<int> _thoiGiaNangBacCu;
        partial void On_ThoiGiaNangBacCu_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_ThoiGiaNangBacCu_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> ThoiGianNangBacMoi
        {
            get
            {
                return _thoiGianNangBacMoi;
            }
            set
            {
    			Nullable<int> oldValue =  _thoiGianNangBacMoi;
    			bool stopChanging = false;
                On_ThoiGianNangBacMoi_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("ThoiGianNangBacMoi");
    			if(!stopChanging)
    			{
    				_thoiGianNangBacMoi = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("ThoiGianNangBacMoi");
    				On_ThoiGianNangBacMoi_Changed(oldValue, _thoiGianNangBacMoi);//\\
    			}
            }
        }
    	public static String ThoiGianNangBacMoi_PropertyName { get { return "ThoiGianNangBacMoi"; } }
        private Nullable<int> _thoiGianNangBacMoi;
        partial void On_ThoiGianNangBacMoi_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_ThoiGianNangBacMoi_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaNgachCoBanCu
        {
            get
            {
                return _maNgachCoBanCu;
            }
            set
            {
    			Nullable<int> oldValue =  _maNgachCoBanCu;
    			bool stopChanging = false;
                On_MaNgachCoBanCu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaNgachCoBanCu");
    			if(!stopChanging)
    			{
    				_maNgachCoBanCu = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaNgachCoBanCu");
    				On_MaNgachCoBanCu_Changed(oldValue, _maNgachCoBanCu);//\\
    			}
            }
        }
    	public static String MaNgachCoBanCu_PropertyName { get { return "MaNgachCoBanCu"; } }
        private Nullable<int> _maNgachCoBanCu;
        partial void On_MaNgachCoBanCu_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaNgachCoBanCu_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaBacLuongCoBanCu
        {
            get
            {
                return _maBacLuongCoBanCu;
            }
            set
            {
    			Nullable<int> oldValue =  _maBacLuongCoBanCu;
    			bool stopChanging = false;
                On_MaBacLuongCoBanCu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaBacLuongCoBanCu");
    			if(!stopChanging)
    			{
    				_maBacLuongCoBanCu = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaBacLuongCoBanCu");
    				On_MaBacLuongCoBanCu_Changed(oldValue, _maBacLuongCoBanCu);//\\
    			}
            }
        }
    	public static String MaBacLuongCoBanCu_PropertyName { get { return "MaBacLuongCoBanCu"; } }
        private Nullable<int> _maBacLuongCoBanCu;
        partial void On_MaBacLuongCoBanCu_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaBacLuongCoBanCu_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaNgachLuongCoBanMoi
        {
            get
            {
                return _maNgachLuongCoBanMoi;
            }
            set
            {
    			Nullable<int> oldValue =  _maNgachLuongCoBanMoi;
    			bool stopChanging = false;
                On_MaNgachLuongCoBanMoi_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaNgachLuongCoBanMoi");
    			if(!stopChanging)
    			{
    				_maNgachLuongCoBanMoi = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaNgachLuongCoBanMoi");
    				On_MaNgachLuongCoBanMoi_Changed(oldValue, _maNgachLuongCoBanMoi);//\\
    			}
            }
        }
    	public static String MaNgachLuongCoBanMoi_PropertyName { get { return "MaNgachLuongCoBanMoi"; } }
        private Nullable<int> _maNgachLuongCoBanMoi;
        partial void On_MaNgachLuongCoBanMoi_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaNgachLuongCoBanMoi_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaBacLuongCoBanMoi
        {
            get
            {
                return _maBacLuongCoBanMoi;
            }
            set
            {
    			Nullable<int> oldValue =  _maBacLuongCoBanMoi;
    			bool stopChanging = false;
                On_MaBacLuongCoBanMoi_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaBacLuongCoBanMoi");
    			if(!stopChanging)
    			{
    				_maBacLuongCoBanMoi = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaBacLuongCoBanMoi");
    				On_MaBacLuongCoBanMoi_Changed(oldValue, _maBacLuongCoBanMoi);//\\
    			}
            }
        }
    	public static String MaBacLuongCoBanMoi_PropertyName { get { return "MaBacLuongCoBanMoi"; } }
        private Nullable<int> _maBacLuongCoBanMoi;
        partial void On_MaBacLuongCoBanMoi_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaBacLuongCoBanMoi_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaBacBaoHiemCu
        {
            get
            {
                return _maBacBaoHiemCu;
            }
            set
            {
    			Nullable<int> oldValue =  _maBacBaoHiemCu;
    			bool stopChanging = false;
                On_MaBacBaoHiemCu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaBacBaoHiemCu");
    			if(!stopChanging)
    			{
    				_maBacBaoHiemCu = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaBacBaoHiemCu");
    				On_MaBacBaoHiemCu_Changed(oldValue, _maBacBaoHiemCu);//\\
    			}
            }
        }
    	public static String MaBacBaoHiemCu_PropertyName { get { return "MaBacBaoHiemCu"; } }
        private Nullable<int> _maBacBaoHiemCu;
        partial void On_MaBacBaoHiemCu_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaBacBaoHiemCu_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> HeSoBaoHiemCu
        {
            get
            {
                return _heSoBaoHiemCu;
            }
            set
            {
    			Nullable<decimal> oldValue =  _heSoBaoHiemCu;
    			bool stopChanging = false;
                On_HeSoBaoHiemCu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("HeSoBaoHiemCu");
    			if(!stopChanging)
    			{
    				_heSoBaoHiemCu = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("HeSoBaoHiemCu");
    				On_HeSoBaoHiemCu_Changed(oldValue, _heSoBaoHiemCu);//\\
    			}
            }
        }
    	public static String HeSoBaoHiemCu_PropertyName { get { return "HeSoBaoHiemCu"; } }
        private Nullable<decimal> _heSoBaoHiemCu;
        partial void On_HeSoBaoHiemCu_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_HeSoBaoHiemCu_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaBacBaoHiemMoi
        {
            get
            {
                return _maBacBaoHiemMoi;
            }
            set
            {
    			Nullable<int> oldValue =  _maBacBaoHiemMoi;
    			bool stopChanging = false;
                On_MaBacBaoHiemMoi_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaBacBaoHiemMoi");
    			if(!stopChanging)
    			{
    				_maBacBaoHiemMoi = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaBacBaoHiemMoi");
    				On_MaBacBaoHiemMoi_Changed(oldValue, _maBacBaoHiemMoi);//\\
    			}
            }
        }
    	public static String MaBacBaoHiemMoi_PropertyName { get { return "MaBacBaoHiemMoi"; } }
        private Nullable<int> _maBacBaoHiemMoi;
        partial void On_MaBacBaoHiemMoi_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaBacBaoHiemMoi_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> HeSoBaoHiemMoi
        {
            get
            {
                return _heSoBaoHiemMoi;
            }
            set
            {
    			Nullable<decimal> oldValue =  _heSoBaoHiemMoi;
    			bool stopChanging = false;
                On_HeSoBaoHiemMoi_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("HeSoBaoHiemMoi");
    			if(!stopChanging)
    			{
    				_heSoBaoHiemMoi = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("HeSoBaoHiemMoi");
    				On_HeSoBaoHiemMoi_Changed(oldValue, _heSoBaoHiemMoi);//\\
    			}
            }
        }
    	public static String HeSoBaoHiemMoi_PropertyName { get { return "HeSoBaoHiemMoi"; } }
        private Nullable<decimal> _heSoBaoHiemMoi;
        partial void On_HeSoBaoHiemMoi_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_HeSoBaoHiemMoi_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> HeSoLuongMoi
        {
            get
            {
                return _heSoLuongMoi;
            }
            set
            {
    			Nullable<decimal> oldValue =  _heSoLuongMoi;
    			bool stopChanging = false;
                On_HeSoLuongMoi_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("HeSoLuongMoi");
    			if(!stopChanging)
    			{
    				_heSoLuongMoi = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("HeSoLuongMoi");
    				On_HeSoLuongMoi_Changed(oldValue, _heSoLuongMoi);//\\
    			}
            }
        }
    	public static String HeSoLuongMoi_PropertyName { get { return "HeSoLuongMoi"; } }
        private Nullable<decimal> _heSoLuongMoi;
        partial void On_HeSoLuongMoi_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_HeSoLuongMoi_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> HeSoLuongCu
        {
            get
            {
                return _heSoLuongCu;
            }
            set
            {
    			Nullable<decimal> oldValue =  _heSoLuongCu;
    			bool stopChanging = false;
                On_HeSoLuongCu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("HeSoLuongCu");
    			if(!stopChanging)
    			{
    				_heSoLuongCu = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("HeSoLuongCu");
    				On_HeSoLuongCu_Changed(oldValue, _heSoLuongCu);//\\
    			}
            }
        }
    	public static String HeSoLuongCu_PropertyName { get { return "HeSoLuongCu"; } }
        private Nullable<decimal> _heSoLuongCu;
        partial void On_HeSoLuongCu_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_HeSoLuongCu_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaNhomNgachCoBan
        {
            get
            {
                return _maNhomNgachCoBan;
            }
            set
            {
    			Nullable<int> oldValue =  _maNhomNgachCoBan;
    			bool stopChanging = false;
                On_MaNhomNgachCoBan_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaNhomNgachCoBan");
    			if(!stopChanging)
    			{
    				_maNhomNgachCoBan = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaNhomNgachCoBan");
    				On_MaNhomNgachCoBan_Changed(oldValue, _maNhomNgachCoBan);//\\
    			}
            }
        }
    	public static String MaNhomNgachCoBan_PropertyName { get { return "MaNhomNgachCoBan"; } }
        private Nullable<int> _maNhomNgachCoBan;
        partial void On_MaNhomNgachCoBan_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaNhomNgachCoBan_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<bool> TraLuongQuaTK
        {
            get
            {
                return _traLuongQuaTK;
            }
            set
            {
    			Nullable<bool> oldValue =  _traLuongQuaTK;
    			bool stopChanging = false;
                On_TraLuongQuaTK_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TraLuongQuaTK");
    			if(!stopChanging)
    			{
    				_traLuongQuaTK = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("TraLuongQuaTK");
    				On_TraLuongQuaTK_Changed(oldValue, _traLuongQuaTK);//\\
    			}
            }
        }
    	public static String TraLuongQuaTK_PropertyName { get { return "TraLuongQuaTK"; } }
        private Nullable<bool> _traLuongQuaTK;
        partial void On_TraLuongQuaTK_Changing(Nullable<bool> currentValue, ref Nullable<bool> newValue, ref bool stopChanging);
        partial void On_TraLuongQuaTK_Changed(Nullable<bool> oldValue, Nullable<bool> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> HSVKBHCu
        {
            get
            {
                return _hSVKBHCu;
            }
            set
            {
    			Nullable<decimal> oldValue =  _hSVKBHCu;
    			bool stopChanging = false;
                On_HSVKBHCu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("HSVKBHCu");
    			if(!stopChanging)
    			{
    				_hSVKBHCu = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("HSVKBHCu");
    				On_HSVKBHCu_Changed(oldValue, _hSVKBHCu);//\\
    			}
            }
        }
    	public static String HSVKBHCu_PropertyName { get { return "HSVKBHCu"; } }
        private Nullable<decimal> _hSVKBHCu;
        partial void On_HSVKBHCu_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_HSVKBHCu_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> HSVKBHMoi
        {
            get
            {
                return _hSVKBHMoi;
            }
            set
            {
    			Nullable<decimal> oldValue =  _hSVKBHMoi;
    			bool stopChanging = false;
                On_HSVKBHMoi_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("HSVKBHMoi");
    			if(!stopChanging)
    			{
    				_hSVKBHMoi = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("HSVKBHMoi");
    				On_HSVKBHMoi_Changed(oldValue, _hSVKBHMoi);//\\
    			}
            }
        }
    	public static String HSVKBHMoi_PropertyName { get { return "HSVKBHMoi"; } }
        private Nullable<decimal> _hSVKBHMoi;
        partial void On_HSVKBHMoi_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_HSVKBHMoi_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> KieuNangLuong
        {
            get
            {
                return _kieuNangLuong;
            }
            set
            {
    			Nullable<int> oldValue =  _kieuNangLuong;
    			bool stopChanging = false;
                On_KieuNangLuong_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("KieuNangLuong");
    			if(!stopChanging)
    			{
    				_kieuNangLuong = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("KieuNangLuong");
    				On_KieuNangLuong_Changed(oldValue, _kieuNangLuong);//\\
    			}
            }
        }
    	public static String KieuNangLuong_PropertyName { get { return "KieuNangLuong"; } }
        private Nullable<int> _kieuNangLuong;
        partial void On_KieuNangLuong_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_KieuNangLuong_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> HeSoNBCu
        {
            get
            {
                return _heSoNBCu;
            }
            set
            {
    			Nullable<decimal> oldValue =  _heSoNBCu;
    			bool stopChanging = false;
                On_HeSoNBCu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("HeSoNBCu");
    			if(!stopChanging)
    			{
    				_heSoNBCu = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("HeSoNBCu");
    				On_HeSoNBCu_Changed(oldValue, _heSoNBCu);//\\
    			}
            }
        }
    	public static String HeSoNBCu_PropertyName { get { return "HeSoNBCu"; } }
        private Nullable<decimal> _heSoNBCu;
        partial void On_HeSoNBCu_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_HeSoNBCu_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> HeSoNBMoi
        {
            get
            {
                return _heSoNBMoi;
            }
            set
            {
    			Nullable<decimal> oldValue =  _heSoNBMoi;
    			bool stopChanging = false;
                On_HeSoNBMoi_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("HeSoNBMoi");
    			if(!stopChanging)
    			{
    				_heSoNBMoi = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("HeSoNBMoi");
    				On_HeSoNBMoi_Changed(oldValue, _heSoNBMoi);//\\
    			}
            }
        }
    	public static String HeSoNBMoi_PropertyName { get { return "HeSoNBMoi"; } }
        private Nullable<decimal> _heSoNBMoi;
        partial void On_HeSoNBMoi_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_HeSoNBMoi_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> LoaiNhanVienCu
        {
            get
            {
                return _loaiNhanVienCu;
            }
            set
            {
    			Nullable<int> oldValue =  _loaiNhanVienCu;
    			bool stopChanging = false;
                On_LoaiNhanVienCu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("LoaiNhanVienCu");
    			if(!stopChanging)
    			{
    				_loaiNhanVienCu = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("LoaiNhanVienCu");
    				On_LoaiNhanVienCu_Changed(oldValue, _loaiNhanVienCu);//\\
    			}
            }
        }
    	public static String LoaiNhanVienCu_PropertyName { get { return "LoaiNhanVienCu"; } }
        private Nullable<int> _loaiNhanVienCu;
        partial void On_LoaiNhanVienCu_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_LoaiNhanVienCu_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> LoaiNhanVienMoi
        {
            get
            {
                return _loaiNhanVienMoi;
            }
            set
            {
    			Nullable<int> oldValue =  _loaiNhanVienMoi;
    			bool stopChanging = false;
                On_LoaiNhanVienMoi_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("LoaiNhanVienMoi");
    			if(!stopChanging)
    			{
    				_loaiNhanVienMoi = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("LoaiNhanVienMoi");
    				On_LoaiNhanVienMoi_Changed(oldValue, _loaiNhanVienMoi);//\\
    			}
            }
        }
    	public static String LoaiNhanVienMoi_PropertyName { get { return "LoaiNhanVienMoi"; } }
        private Nullable<int> _loaiNhanVienMoi;
        partial void On_LoaiNhanVienMoi_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_LoaiNhanVienMoi_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> NgaySua
        {
            get
            {
                return _ngaySua;
            }
            set
            {
    			Nullable<System.DateTime> oldValue =  _ngaySua;
    			bool stopChanging = false;
                On_NgaySua_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("NgaySua");
    			if(!stopChanging)
    			{
    				_ngaySua = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("NgaySua");
    				On_NgaySua_Changed(oldValue, _ngaySua);//\\
    			}
            }
        }
    	public static String NgaySua_PropertyName { get { return "NgaySua"; } }
        private Nullable<System.DateTime> _ngaySua;
        partial void On_NgaySua_Changing(Nullable<System.DateTime> currentValue, ref Nullable<System.DateTime> newValue, ref bool stopChanging);
        partial void On_NgaySua_Changed(Nullable<System.DateTime> oldValue, Nullable<System.DateTime> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<bool> CapNhatSau
        {
            get
            {
                return _capNhatSau;
            }
            set
            {
    			Nullable<bool> oldValue =  _capNhatSau;
    			bool stopChanging = false;
                On_CapNhatSau_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("CapNhatSau");
    			if(!stopChanging)
    			{
    				_capNhatSau = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("CapNhatSau");
    				On_CapNhatSau_Changed(oldValue, _capNhatSau);//\\
    			}
            }
        }
    	public static String CapNhatSau_PropertyName { get { return "CapNhatSau"; } }
        private Nullable<bool> _capNhatSau;
        partial void On_CapNhatSau_Changing(Nullable<bool> currentValue, ref Nullable<bool> newValue, ref bool stopChanging);
        partial void On_CapNhatSau_Changed(Nullable<bool> oldValue, Nullable<bool> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> MocNangLuong
        {
            get
            {
                return _mocNangLuong;
            }
            set
            {
    			Nullable<System.DateTime> oldValue =  _mocNangLuong;
    			bool stopChanging = false;
                On_MocNangLuong_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MocNangLuong");
    			if(!stopChanging)
    			{
    				_mocNangLuong = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MocNangLuong");
    				On_MocNangLuong_Changed(oldValue, _mocNangLuong);//\\
    			}
            }
        }
    	public static String MocNangLuong_PropertyName { get { return "MocNangLuong"; } }
        private Nullable<System.DateTime> _mocNangLuong;
        partial void On_MocNangLuong_Changing(Nullable<System.DateTime> currentValue, ref Nullable<System.DateTime> newValue, ref bool stopChanging);
        partial void On_MocNangLuong_Changed(Nullable<System.DateTime> oldValue, Nullable<System.DateTime> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> MocNangLuongBH
        {
            get
            {
                return _mocNangLuongBH;
            }
            set
            {
    			Nullable<System.DateTime> oldValue =  _mocNangLuongBH;
    			bool stopChanging = false;
                On_MocNangLuongBH_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MocNangLuongBH");
    			if(!stopChanging)
    			{
    				_mocNangLuongBH = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MocNangLuongBH");
    				On_MocNangLuongBH_Changed(oldValue, _mocNangLuongBH);//\\
    			}
            }
        }
    	public static String MocNangLuongBH_PropertyName { get { return "MocNangLuongBH"; } }
        private Nullable<System.DateTime> _mocNangLuongBH;
        partial void On_MocNangLuongBH_Changing(Nullable<System.DateTime> currentValue, ref Nullable<System.DateTime> newValue, ref bool stopChanging);
        partial void On_MocNangLuongBH_Changed(Nullable<System.DateTime> oldValue, Nullable<System.DateTime> currentValue);

        #endregion

    }
}
