//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi DESKTOP-J5VELTF\DELL luc 10:47:32 ngay 24/12/2021
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace PSC_ERP_Business.Main.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PSC_ERPModel", Name="v_LayDuLieuCuImport")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class v_LayDuLieuCuImport : PSC_ERP_Core.BaseEntityObject//EntityObject
    {
    	public v_LayDuLieuCuImport()
    	{
    
    	}
        #region Factory Method
    
        /// <summary>
        /// Create a new v_LayDuLieuCuImport object.
        /// </summary>
        /// <param name="loaiCT">Initial value of the LoaiCT property.</param>
        /// <param name="soTienMuc">Initial value of the SoTienMuc property.</param>
        /// <param name="ban">Initial value of the Ban property.</param>
        /// <param name="nguoiLap">Initial value of the NguoiLap property.</param>
        public static v_LayDuLieuCuImport Createv_LayDuLieuCuImport(int loaiCT, int soTienMuc, string ban, string nguoiLap)
        {
            v_LayDuLieuCuImport v_LayDuLieuCuImport = new v_LayDuLieuCuImport();
            v_LayDuLieuCuImport.LoaiCT = loaiCT;
            v_LayDuLieuCuImport.SoTienMuc = soTienMuc;
            v_LayDuLieuCuImport.Ban = ban;
            v_LayDuLieuCuImport.NguoiLap = nguoiLap;
            return v_LayDuLieuCuImport;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string SoCT
        {
            get
            {
                return _soCT;
            }
            set
            {
    			string oldValue =  _soCT;
    			bool stopChanging = false;
                On_SoCT_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("SoCT");
    			if(!stopChanging)
    			{
    				_soCT = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("SoCT");
    				On_SoCT_Changed(oldValue, _soCT);//\\
    			}
            }
        }
    	public static String SoCT_PropertyName { get { return "SoCT"; } }
        private string _soCT;
        partial void On_SoCT_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_SoCT_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> ngay
        {
            get
            {
                return _ngay;
            }
            set
            {
    			Nullable<System.DateTime> oldValue =  _ngay;
    			bool stopChanging = false;
                On_ngay_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("ngay");
    			if(!stopChanging)
    			{
    				_ngay = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("ngay");
    				On_ngay_Changed(oldValue, _ngay);//\\
    			}
            }
        }
    	public static String ngay_PropertyName { get { return "ngay"; } }
        private Nullable<System.DateTime> _ngay;
        partial void On_ngay_Changing(Nullable<System.DateTime> currentValue, ref Nullable<System.DateTime> newValue, ref bool stopChanging);
        partial void On_ngay_Changed(Nullable<System.DateTime> oldValue, Nullable<System.DateTime> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<double> sotien
        {
            get
            {
                return _sotien;
            }
            set
            {
    			Nullable<double> oldValue =  _sotien;
    			bool stopChanging = false;
                On_sotien_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("sotien");
    			if(!stopChanging)
    			{
    				_sotien = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("sotien");
    				On_sotien_Changed(oldValue, _sotien);//\\
    			}
            }
        }
    	public static String sotien_PropertyName { get { return "sotien"; } }
        private Nullable<double> _sotien;
        partial void On_sotien_Changing(Nullable<double> currentValue, ref Nullable<double> newValue, ref bool stopChanging);
        partial void On_sotien_Changed(Nullable<double> oldValue, Nullable<double> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<double> tygia
        {
            get
            {
                return _tygia;
            }
            set
            {
    			Nullable<double> oldValue =  _tygia;
    			bool stopChanging = false;
                On_tygia_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("tygia");
    			if(!stopChanging)
    			{
    				_tygia = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("tygia");
    				On_tygia_Changed(oldValue, _tygia);//\\
    			}
            }
        }
    	public static String tygia_PropertyName { get { return "tygia"; } }
        private Nullable<double> _tygia;
        partial void On_tygia_Changing(Nullable<double> currentValue, ref Nullable<double> newValue, ref bool stopChanging);
        partial void On_tygia_Changed(Nullable<double> oldValue, Nullable<double> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<double> ThanhTien
        {
            get
            {
                return _thanhTien;
            }
            set
            {
    			Nullable<double> oldValue =  _thanhTien;
    			bool stopChanging = false;
                On_ThanhTien_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("ThanhTien");
    			if(!stopChanging)
    			{
    				_thanhTien = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("ThanhTien");
    				On_ThanhTien_Changed(oldValue, _thanhTien);//\\
    			}
            }
        }
    	public static String ThanhTien_PropertyName { get { return "ThanhTien"; } }
        private Nullable<double> _thanhTien;
        partial void On_ThanhTien_Changing(Nullable<double> currentValue, ref Nullable<double> newValue, ref bool stopChanging);
        partial void On_ThanhTien_Changed(Nullable<double> oldValue, Nullable<double> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string DienGiai
        {
            get
            {
                return _dienGiai;
            }
            set
            {
    			string oldValue =  _dienGiai;
    			bool stopChanging = false;
                On_DienGiai_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("DienGiai");
    			if(!stopChanging)
    			{
    				_dienGiai = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("DienGiai");
    				On_DienGiai_Changed(oldValue, _dienGiai);//\\
    			}
            }
        }
    	public static String DienGiai_PropertyName { get { return "DienGiai"; } }
        private string _dienGiai;
        partial void On_DienGiai_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_DienGiai_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public int LoaiCT
        {
            get
            {
                return _loaiCT;
            }
            set
            {
                if (_loaiCT != value)
                {
        			int oldValue =  _loaiCT;
        			bool stopChanging = false;
                    On_LoaiCT_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("LoaiCT");
        			if(!stopChanging)
        			{
        				_loaiCT = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("LoaiCT");
        				On_LoaiCT_Changed(oldValue, _loaiCT);//\\
        			}
                }
            }
        }
    	public static String LoaiCT_PropertyName { get { return "LoaiCT"; } }
        private int _loaiCT;
        partial void On_LoaiCT_Changing(int currentValue, ref int newValue, ref bool stopChanging);
        partial void On_LoaiCT_Changed(int oldValue, int currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string dkno
        {
            get
            {
                return _dkno;
            }
            set
            {
    			string oldValue =  _dkno;
    			bool stopChanging = false;
                On_dkno_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("dkno");
    			if(!stopChanging)
    			{
    				_dkno = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("dkno");
    				On_dkno_Changed(oldValue, _dkno);//\\
    			}
            }
        }
    	public static String dkno_PropertyName { get { return "dkno"; } }
        private string _dkno;
        partial void On_dkno_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_dkno_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string dkco
        {
            get
            {
                return _dkco;
            }
            set
            {
    			string oldValue =  _dkco;
    			bool stopChanging = false;
                On_dkco_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("dkco");
    			if(!stopChanging)
    			{
    				_dkco = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("dkco");
    				On_dkco_Changed(oldValue, _dkco);//\\
    			}
            }
        }
    	public static String dkco_PropertyName { get { return "dkco"; } }
        private string _dkco;
        partial void On_dkco_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_dkco_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<double> SoTienBT
        {
            get
            {
                return _soTienBT;
            }
            set
            {
    			Nullable<double> oldValue =  _soTienBT;
    			bool stopChanging = false;
                On_SoTienBT_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("SoTienBT");
    			if(!stopChanging)
    			{
    				_soTienBT = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("SoTienBT");
    				On_SoTienBT_Changed(oldValue, _soTienBT);//\\
    			}
            }
        }
    	public static String SoTienBT_PropertyName { get { return "SoTienBT"; } }
        private Nullable<double> _soTienBT;
        partial void On_SoTienBT_Changing(Nullable<double> currentValue, ref Nullable<double> newValue, ref bool stopChanging);
        partial void On_SoTienBT_Changed(Nullable<double> oldValue, Nullable<double> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string DienGiaiBT
        {
            get
            {
                return _dienGiaiBT;
            }
            set
            {
    			string oldValue =  _dienGiaiBT;
    			bool stopChanging = false;
                On_DienGiaiBT_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("DienGiaiBT");
    			if(!stopChanging)
    			{
    				_dienGiaiBT = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("DienGiaiBT");
    				On_DienGiaiBT_Changed(oldValue, _dienGiaiBT);//\\
    			}
            }
        }
    	public static String DienGiaiBT_PropertyName { get { return "DienGiaiBT"; } }
        private string _dienGiaiBT;
        partial void On_DienGiaiBT_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_DienGiaiBT_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaTieuMuc
        {
            get
            {
                return _maTieuMuc;
            }
            set
            {
    			Nullable<int> oldValue =  _maTieuMuc;
    			bool stopChanging = false;
                On_MaTieuMuc_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaTieuMuc");
    			if(!stopChanging)
    			{
    				_maTieuMuc = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaTieuMuc");
    				On_MaTieuMuc_Changed(oldValue, _maTieuMuc);//\\
    			}
            }
        }
    	public static String MaTieuMuc_PropertyName { get { return "MaTieuMuc"; } }
        private Nullable<int> _maTieuMuc;
        partial void On_MaTieuMuc_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaTieuMuc_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public int SoTienMuc
        {
            get
            {
                return _soTienMuc;
            }
            set
            {
                if (_soTienMuc != value)
                {
        			int oldValue =  _soTienMuc;
        			bool stopChanging = false;
                    On_SoTienMuc_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("SoTienMuc");
        			if(!stopChanging)
        			{
        				_soTienMuc = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("SoTienMuc");
        				On_SoTienMuc_Changed(oldValue, _soTienMuc);//\\
        			}
                }
            }
        }
    	public static String SoTienMuc_PropertyName { get { return "SoTienMuc"; } }
        private int _soTienMuc;
        partial void On_SoTienMuc_Changing(int currentValue, ref int newValue, ref bool stopChanging);
        partial void On_SoTienMuc_Changed(int oldValue, int currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> DienGiaiMuc
        {
            get
            {
                return _dienGiaiMuc;
            }
            set
            {
    			Nullable<int> oldValue =  _dienGiaiMuc;
    			bool stopChanging = false;
                On_DienGiaiMuc_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("DienGiaiMuc");
    			if(!stopChanging)
    			{
    				_dienGiaiMuc = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("DienGiaiMuc");
    				On_DienGiaiMuc_Changed(oldValue, _dienGiaiMuc);//\\
    			}
            }
        }
    	public static String DienGiaiMuc_PropertyName { get { return "DienGiaiMuc"; } }
        private Nullable<int> _dienGiaiMuc;
        partial void On_DienGiaiMuc_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_DienGiaiMuc_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaMuc
        {
            get
            {
                return _maMuc;
            }
            set
            {
    			Nullable<int> oldValue =  _maMuc;
    			bool stopChanging = false;
                On_MaMuc_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaMuc");
    			if(!stopChanging)
    			{
    				_maMuc = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaMuc");
    				On_MaMuc_Changed(oldValue, _maMuc);//\\
    			}
            }
        }
    	public static String MaMuc_PropertyName { get { return "MaMuc"; } }
        private Nullable<int> _maMuc;
        partial void On_MaMuc_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaMuc_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string TenKhachHang
        {
            get
            {
                return _tenKhachHang;
            }
            set
            {
    			string oldValue =  _tenKhachHang;
    			bool stopChanging = false;
                On_TenKhachHang_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TenKhachHang");
    			if(!stopChanging)
    			{
    				_tenKhachHang = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("TenKhachHang");
    				On_TenKhachHang_Changed(oldValue, _tenKhachHang);//\\
    			}
            }
        }
    	public static String TenKhachHang_PropertyName { get { return "TenKhachHang"; } }
        private string _tenKhachHang;
        partial void On_TenKhachHang_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenKhachHang_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> DiaChiKH
        {
            get
            {
                return _diaChiKH;
            }
            set
            {
    			Nullable<int> oldValue =  _diaChiKH;
    			bool stopChanging = false;
                On_DiaChiKH_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("DiaChiKH");
    			if(!stopChanging)
    			{
    				_diaChiKH = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("DiaChiKH");
    				On_DiaChiKH_Changed(oldValue, _diaChiKH);//\\
    			}
            }
        }
    	public static String DiaChiKH_PropertyName { get { return "DiaChiKH"; } }
        private Nullable<int> _diaChiKH;
        partial void On_DiaChiKH_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_DiaChiKH_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> KhachHangNgoai
        {
            get
            {
                return _khachHangNgoai;
            }
            set
            {
    			Nullable<int> oldValue =  _khachHangNgoai;
    			bool stopChanging = false;
                On_KhachHangNgoai_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("KhachHangNgoai");
    			if(!stopChanging)
    			{
    				_khachHangNgoai = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("KhachHangNgoai");
    				On_KhachHangNgoai_Changed(oldValue, _khachHangNgoai);//\\
    			}
            }
        }
    	public static String KhachHangNgoai_PropertyName { get { return "KhachHangNgoai"; } }
        private Nullable<int> _khachHangNgoai;
        partial void On_KhachHangNgoai_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_KhachHangNgoai_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> DiaChiKHNgoai
        {
            get
            {
                return _diaChiKHNgoai;
            }
            set
            {
    			Nullable<int> oldValue =  _diaChiKHNgoai;
    			bool stopChanging = false;
                On_DiaChiKHNgoai_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("DiaChiKHNgoai");
    			if(!stopChanging)
    			{
    				_diaChiKHNgoai = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("DiaChiKHNgoai");
    				On_DiaChiKHNgoai_Changed(oldValue, _diaChiKHNgoai);//\\
    			}
            }
        }
    	public static String DiaChiKHNgoai_PropertyName { get { return "DiaChiKHNgoai"; } }
        private Nullable<int> _diaChiKHNgoai;
        partial void On_DiaChiKHNgoai_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_DiaChiKHNgoai_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public string Ban
        {
            get
            {
                return _ban;
            }
            set
            {
                if (_ban != value)
                {
        			string oldValue =  _ban;
        			bool stopChanging = false;
                    On_Ban_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("Ban");
        			if(!stopChanging)
        			{
        				_ban = StructuralObject.SetValidValue(value, false);
        				ReportPropertyChanged("Ban");
        				On_Ban_Changed(oldValue, _ban);//\\
        			}
                }
            }
        }
    	public static String Ban_PropertyName { get { return "Ban"; } }
        private string _ban;
        partial void On_Ban_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_Ban_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public string NguoiLap
        {
            get
            {
                return _nguoiLap;
            }
            set
            {
                if (_nguoiLap != value)
                {
        			string oldValue =  _nguoiLap;
        			bool stopChanging = false;
                    On_NguoiLap_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("NguoiLap");
        			if(!stopChanging)
        			{
        				_nguoiLap = StructuralObject.SetValidValue(value, false);
        				ReportPropertyChanged("NguoiLap");
        				On_NguoiLap_Changed(oldValue, _nguoiLap);//\\
        			}
                }
            }
        }
    	public static String NguoiLap_PropertyName { get { return "NguoiLap"; } }
        private string _nguoiLap;
        partial void On_NguoiLap_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_NguoiLap_Changed(string oldValue, string currentValue);

        #endregion

    }
}
