//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi DESKTOP-J5VELTF\DELL luc 10:47:32 ngay 24/12/2021
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace PSC_ERP_Business.Main.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PSC_ERPModel", Name="v_TinhTongThuChiuThue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class v_TinhTongThuChiuThue : PSC_ERP_Core.BaseEntityObject//EntityObject
    {
    	public v_TinhTongThuChiuThue()
    	{
    
    	}
        #region Factory Method
    
        /// <summary>
        /// Create a new v_TinhTongThuChiuThue object.
        /// </summary>
        /// <param name="maKyTinhLuong">Initial value of the MaKyTinhLuong property.</param>
        /// <param name="maNhanVien">Initial value of the MaNhanVien property.</param>
        /// <param name="tenLoaiPhuCap">Initial value of the TenLoaiPhuCap property.</param>
        /// <param name="tenPhuCap">Initial value of the TenPhuCap property.</param>
        public static v_TinhTongThuChiuThue Createv_TinhTongThuChiuThue(int maKyTinhLuong, long maNhanVien, string tenLoaiPhuCap, string tenPhuCap)
        {
            v_TinhTongThuChiuThue v_TinhTongThuChiuThue = new v_TinhTongThuChiuThue();
            v_TinhTongThuChiuThue.MaKyTinhLuong = maKyTinhLuong;
            v_TinhTongThuChiuThue.MaNhanVien = maNhanVien;
            v_TinhTongThuChiuThue.TenLoaiPhuCap = tenLoaiPhuCap;
            v_TinhTongThuChiuThue.TenPhuCap = tenPhuCap;
            return v_TinhTongThuChiuThue;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public int MaKyTinhLuong
        {
            get
            {
                return _maKyTinhLuong;
            }
            set
            {
                if (_maKyTinhLuong != value)
                {
        			int oldValue =  _maKyTinhLuong;
        			bool stopChanging = false;
                    On_MaKyTinhLuong_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("MaKyTinhLuong");
        			if(!stopChanging)
        			{
        				_maKyTinhLuong = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("MaKyTinhLuong");
        				On_MaKyTinhLuong_Changed(oldValue, _maKyTinhLuong);//\\
        			}
                }
            }
        }
    	public static String MaKyTinhLuong_PropertyName { get { return "MaKyTinhLuong"; } }
        private int _maKyTinhLuong;
        partial void On_MaKyTinhLuong_Changing(int currentValue, ref int newValue, ref bool stopChanging);
        partial void On_MaKyTinhLuong_Changed(int oldValue, int currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public long MaNhanVien
        {
            get
            {
                return _maNhanVien;
            }
            set
            {
                if (_maNhanVien != value)
                {
        			long oldValue =  _maNhanVien;
        			bool stopChanging = false;
                    On_MaNhanVien_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("MaNhanVien");
        			if(!stopChanging)
        			{
        				_maNhanVien = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("MaNhanVien");
        				On_MaNhanVien_Changed(oldValue, _maNhanVien);//\\
        			}
                }
            }
        }
    	public static String MaNhanVien_PropertyName { get { return "MaNhanVien"; } }
        private long _maNhanVien;
        partial void On_MaNhanVien_Changing(long currentValue, ref long newValue, ref bool stopChanging);
        partial void On_MaNhanVien_Changed(long oldValue, long currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string MaQLLoaiPhuCap
        {
            get
            {
                return _maQLLoaiPhuCap;
            }
            set
            {
    			string oldValue =  _maQLLoaiPhuCap;
    			bool stopChanging = false;
                On_MaQLLoaiPhuCap_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaQLLoaiPhuCap");
    			if(!stopChanging)
    			{
    				_maQLLoaiPhuCap = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("MaQLLoaiPhuCap");
    				On_MaQLLoaiPhuCap_Changed(oldValue, _maQLLoaiPhuCap);//\\
    			}
            }
        }
    	public static String MaQLLoaiPhuCap_PropertyName { get { return "MaQLLoaiPhuCap"; } }
        private string _maQLLoaiPhuCap;
        partial void On_MaQLLoaiPhuCap_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_MaQLLoaiPhuCap_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public string TenLoaiPhuCap
        {
            get
            {
                return _tenLoaiPhuCap;
            }
            set
            {
                if (_tenLoaiPhuCap != value)
                {
        			string oldValue =  _tenLoaiPhuCap;
        			bool stopChanging = false;
                    On_TenLoaiPhuCap_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("TenLoaiPhuCap");
        			if(!stopChanging)
        			{
        				_tenLoaiPhuCap = StructuralObject.SetValidValue(value, false);
        				ReportPropertyChanged("TenLoaiPhuCap");
        				On_TenLoaiPhuCap_Changed(oldValue, _tenLoaiPhuCap);//\\
        			}
                }
            }
        }
    	public static String TenLoaiPhuCap_PropertyName { get { return "TenLoaiPhuCap"; } }
        private string _tenLoaiPhuCap;
        partial void On_TenLoaiPhuCap_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenLoaiPhuCap_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> PTThuNhapTinhThue
        {
            get
            {
                return _pTThuNhapTinhThue;
            }
            set
            {
    			Nullable<int> oldValue =  _pTThuNhapTinhThue;
    			bool stopChanging = false;
                On_PTThuNhapTinhThue_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("PTThuNhapTinhThue");
    			if(!stopChanging)
    			{
    				_pTThuNhapTinhThue = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("PTThuNhapTinhThue");
    				On_PTThuNhapTinhThue_Changed(oldValue, _pTThuNhapTinhThue);//\\
    			}
            }
        }
    	public static String PTThuNhapTinhThue_PropertyName { get { return "PTThuNhapTinhThue"; } }
        private Nullable<int> _pTThuNhapTinhThue;
        partial void On_PTThuNhapTinhThue_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_PTThuNhapTinhThue_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public string TenPhuCap
        {
            get
            {
                return _tenPhuCap;
            }
            set
            {
                if (_tenPhuCap != value)
                {
        			string oldValue =  _tenPhuCap;
        			bool stopChanging = false;
                    On_TenPhuCap_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("TenPhuCap");
        			if(!stopChanging)
        			{
        				_tenPhuCap = StructuralObject.SetValidValue(value, false);
        				ReportPropertyChanged("TenPhuCap");
        				On_TenPhuCap_Changed(oldValue, _tenPhuCap);//\\
        			}
                }
            }
        }
    	public static String TenPhuCap_PropertyName { get { return "TenPhuCap"; } }
        private string _tenPhuCap;
        partial void On_TenPhuCap_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenPhuCap_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> PhuCap
        {
            get
            {
                return _phuCap;
            }
            set
            {
    			Nullable<decimal> oldValue =  _phuCap;
    			bool stopChanging = false;
                On_PhuCap_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("PhuCap");
    			if(!stopChanging)
    			{
    				_phuCap = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("PhuCap");
    				On_PhuCap_Changed(oldValue, _phuCap);//\\
    			}
            }
        }
    	public static String PhuCap_PropertyName { get { return "PhuCap"; } }
        private Nullable<decimal> _phuCap;
        partial void On_PhuCap_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_PhuCap_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> TienThue
        {
            get
            {
                return _tienThue;
            }
            set
            {
    			Nullable<decimal> oldValue =  _tienThue;
    			bool stopChanging = false;
                On_TienThue_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TienThue");
    			if(!stopChanging)
    			{
    				_tienThue = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("TienThue");
    				On_TienThue_Changed(oldValue, _tienThue);//\\
    			}
            }
        }
    	public static String TienThue_PropertyName { get { return "TienThue"; } }
        private Nullable<decimal> _tienThue;
        partial void On_TienThue_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_TienThue_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<decimal> TNChiuThue
        {
            get
            {
                return _tNChiuThue;
            }
            set
            {
    			Nullable<decimal> oldValue =  _tNChiuThue;
    			bool stopChanging = false;
                On_TNChiuThue_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TNChiuThue");
    			if(!stopChanging)
    			{
    				_tNChiuThue = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("TNChiuThue");
    				On_TNChiuThue_Changed(oldValue, _tNChiuThue);//\\
    			}
            }
        }
    	public static String TNChiuThue_PropertyName { get { return "TNChiuThue"; } }
        private Nullable<decimal> _tNChiuThue;
        partial void On_TNChiuThue_Changing(Nullable<decimal> currentValue, ref Nullable<decimal> newValue, ref bool stopChanging);
        partial void On_TNChiuThue_Changed(Nullable<decimal> oldValue, Nullable<decimal> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MaBoPhan
        {
            get
            {
                return _maBoPhan;
            }
            set
            {
    			Nullable<int> oldValue =  _maBoPhan;
    			bool stopChanging = false;
                On_MaBoPhan_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaBoPhan");
    			if(!stopChanging)
    			{
    				_maBoPhan = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("MaBoPhan");
    				On_MaBoPhan_Changed(oldValue, _maBoPhan);//\\
    			}
            }
        }
    	public static String MaBoPhan_PropertyName { get { return "MaBoPhan"; } }
        private Nullable<int> _maBoPhan;
        partial void On_MaBoPhan_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_MaBoPhan_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> Nam
        {
            get
            {
                return _nam;
            }
            set
            {
    			Nullable<int> oldValue =  _nam;
    			bool stopChanging = false;
                On_Nam_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("Nam");
    			if(!stopChanging)
    			{
    				_nam = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("Nam");
    				On_Nam_Changed(oldValue, _nam);//\\
    			}
            }
        }
    	public static String Nam_PropertyName { get { return "Nam"; } }
        private Nullable<int> _nam;
        partial void On_Nam_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_Nam_Changed(Nullable<int> oldValue, Nullable<int> currentValue);

        #endregion

    }
}
